apiVersion: v1
kind: Secret
metadata:
    name: blog-db-secrets
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:LZA3aKMjgGUqAVuRcfBnvJJlWfTfKsA+v/rdKTtTcFBuGDJKz4OQeiW+OhJmhIpI2ytYtvH+tb7OW65pQaQVwEEBjJ8tviAy2B8rHh46DKzqbvUBrS7jbRTGEIQg7EIfqdxESF96ZoNE0oyBi5GH9bTB9FcBD0oIQDswvu+Dix3rKqR4EwE2Z2v3ug63m2H3VOiF7iDO/lZifavP,iv:Wz7BRXgUL+L0jYnNGsnS0VX9UfDYKJypXCTdqRFMVrM=,tag:mbwKDUst5VnmtQfv5HiLGw==,type:str]
    DJANGO_SECRET_KEY: ENC[AES256_GCM,data:6tvIrsSAAtakrjc55SiKOvMC5R63n2VQEQhtMnjjV7qbphymek7yF2aAP18R+TN3+0Q=,iv:lApRcH/C/OsmFvXk16DH/mb/IWCzSX/Nw62pWO/X4z0=,tag:nGve3lzcqVMZAeUqBn2Rrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBckVnNTlNMzc5bjR0U0hZ
            VFZzaytCTGJ4c2xROWlZWHEyTHNSWTlvNVRBCnIwdnpvMUQzd284OUw3RXlrRFFG
            VWd1WSt5anhzLzNWYjVPMnhoTDk3MGsKLS0tIE5VMHEvNjZIYzdyRVdHT1hVMEw2
            NFpTN2p4L3VuZ3F4Mnc3eHFLbTVETEUK8Yyc09JC7Ja6BCG34j6qlaZ0weRhGmsY
            W8JdZWrNyGPnGBUmOp8y6FLCTSuVtrg5OuqJU5gdEG2dl5r/mUHkpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T04:47:26Z"
    mac: ENC[AES256_GCM,data:TTfyQux6pO3n3aL/NRhHUKT19Hx7fvi9rGlj4l6bDcHysTH8ND9mhT6vvF7LAClh74d4d++d39WUcCgFVmwOUAaDLfVzFHKqQ0F71B1rT4M3iX533Y5gOBWJuEZgZZDRATakQ6wpCopSFZh7bQds7ArYrdZ16vAv9jMwtSYfkpM=,iv:PDWHPQbJoO5Kn6E90TOZ71Jb9jv7sluT3WswBhpY9wQ=,tag:33g28Y6HZ1eUbDx3QbW9UQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
