apiVersion: v1
kind: Secret
metadata:
    name: blog-db-secrets
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:LZA3aKMjgGUqAVuRcfBnvJJlWfTfKsA+v/rdKTtTcFBuGDJKz4OQeiW+OhJmhIpI2ytYtvH+tb7OW65pQaQVwEEBjJ8tviAy2B8rHh46DKzqbvUBrS7jbRTGEIQg7EIfqdxESF96ZoNE0oyBi5GH9bTB9FcBD0oIQDswvu+Dix3rKqR4EwE2Z2v3ug63m2H3VOiF7iDO/lZifavP,iv:Wz7BRXgUL+L0jYnNGsnS0VX9UfDYKJypXCTdqRFMVrM=,tag:mbwKDUst5VnmtQfv5HiLGw==,type:str]
    DJANGO_SECRET_KEY: ENC[AES256_GCM,data:6tvIrsSAAtakrjc55SiKOvMC5R63n2VQEQhtMnjjV7qbphymek7yF2aAP18R+TN3+0Q=,iv:lApRcH/C/OsmFvXk16DH/mb/IWCzSX/Nw62pWO/X4z0=,tag:nGve3lzcqVMZAeUqBn2Rrg==,type:str]
stringData","SPACES_ACCESS_KEY: DO8016YZEHU9FXZBTDJK
stringData","SPACES_SECRET_KEY: h0Fy0cJd1qoxIxM6mecGBgl6xKKb4P8LL6krw+KpYtQ
stringData","SPACES_BUCKET_NAME: splat-top
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBckVnNTlNMzc5bjR0U0hZ
            VFZzaytCTGJ4c2xROWlZWHEyTHNSWTlvNVRBCnIwdnpvMUQzd284OUw3RXlrRFFG
            VWd1WSt5anhzLzNWYjVPMnhoTDk3MGsKLS0tIE5VMHEvNjZIYzdyRVdHT1hVMEw2
            NFpTN2p4L3VuZ3F4Mnc3eHFLbTVETEUK8Yyc09JC7Ja6BCG34j6qlaZ0weRhGmsY
            W8JdZWrNyGPnGBUmOp8y6FLCTSuVtrg5OuqJU5gdEG2dl5r/mUHkpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T10:12:10Z"
    mac: ENC[AES256_GCM,data:7n7zZAY5S00VpOy7lt8LPmltNbAeq3HtHZlIVP+dlbJ20vYcHn7/e2gL++NP4sM92qvcnXE1deSsk/jhBVnUT1mCq4sgi67wgDMU5wUTLs/AibEzZeSv+IAGSktXrNe9oZSXfjwCGwCHn0w65c9782vefqYd+YdsL8u8VovRGkc=,iv:kqr1qqGtmYMPqeRkEljAZc5/Xru16B3aTpEz5Qohukg=,tag:r1V3w2Z3X1B1gPVweHZ1FQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
