apiVersion: v1
kind: Secret
metadata:
    name: blog-db-secrets
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:/1dVn9DN5dOycR66ztBQ/iL83E3pQ5qVnRYXvUwIdx/BEfp/ibgv/sPqhKKqOEa7Xu6d9cwsRqXq9OViVUk1BUiCJMtAOu5LmlRtg4kGmKsnqTRe9RkMRJdayQvUYhhXHAJru3hUClN3Sjb5Ui7cq2yTGnXFcGUEPsuJtl9kySBy92UVrz+LQzcS2Uf2QuWXnDVqdmhCorAhG2+C,iv:++V/LZsbFPHCZHRO4KkBPJPtbN4QuuUJsTKvn7k+wUg=,tag:laVCpXGY4NbjRML9UpXB9Q==,type:str]
    DJANGO_SECRET_KEY: ENC[AES256_GCM,data:0oO88EXu+e9yN5x7h3JRNK9CyN1VAiR/DzTvM0F3QAJ1ospu4GPSe+LQ60+vHoLSIi0=,iv:vhrxlMs7wvb6NoEXtkEnAVKxsRWas5YR1io8rat7yG0=,tag:hzTxuxFG4R54YUypid0c/w==,type:str]
    SPACES_ACCESS_KEY: ENC[AES256_GCM,data:jS/e6jcCjG9Kz7MMLYMaZy1OL2M=,iv:MD7tx3kizU3PYPAPLPUFbEiAWsst5hP6zlsiFEailfo=,tag:WF9LTK1nD8mA7IdM83T11w==,type:str]
    SPACES_SECRET_KEY: ENC[AES256_GCM,data:TPPtsQ1j65NmyYq6jYmxDwY120Pp5WCiOWWYfnPIaRHh+ZO6CbII03vPZw==,iv:y7IDtSpJYYZRZ7w6rKfi6BzwvTaSaB1B1LHOavW/0Qs=,tag:x6nFt+Hx9jCWORBDVbgm7A==,type:str]
    SPACES_BUCKET_NAME: ENC[AES256_GCM,data:JPOdyl49hgDt,iv:8y7Rmbd1gC5z40IXgSD+chxTSJhCO3a40vW5+Jajj6o=,tag:12jZx4Vv49q9duBfvvcLOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcCs1aHV3V0lRbk1BeEI3
            UngwS2gvc0czUWdJUEdJblhmWVRzVTQ0azBZCkUrWEt4bjhwSS9RVTNiQld1NWQ0
            UTd1cVltWkNkMkI0anl0S24zUlBZamsKLS0tIGNIWnZ6ZnVWL2x2WGNNbmZiZmRk
            SVFFWGNUNDQ4dG13T0U5NkhvN3hJYVkK6lpAaKAINkW2JsPIuF0ConedeIGuGZWD
            OWxdupTSKe/dXPr1FTyazDScsyNHNXRDyRaHbNmhZV+kHIIrQHJaRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T10:32:58Z"
    mac: ENC[AES256_GCM,data:vvHLSj+e+jVgflrsXNzGfHX9gyuAkrPjPQCMCPm5q9dOElhwHh10kEKMbLL6bW+JTXz1xAVWKmgX9UyHMX796kaVg9X7mo4BycOLzutqQU0wxB9I8UNFR7ZmMeweVAZtqNBJltmniWBt9o/k7R92qTVfAa0tu1EHvxblmpSfg9U=,iv:pdvaA9/Ud2eIJm6aI2nQjXdomkUYJGzqVCCg3zBisU4=,tag:MQSutHz9/+N4fVeaRabRAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
