apiVersion: v1
kind: Secret
metadata:
    name: poetry-database
    namespace: poetry
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:GbTsTbDhJq1BpXzgI5iHU4rPs+xRuFrV4FhGG97uJMkVCfTwHboerbVE3+iOlqYrKnaiQuiRnGTYt3QhbM95ZCRgWOv3OtM8rTk7zOWEH9D8UR5JIDkYqlQnXLqYzZlhUSmg8OZPNegSepyV7ZlLVCJoxOHiaPRmxlqNbZ4ehmsS78cMF9/+/IcWp4Yv/9DOAUv0sSVb3fNPd+VSjQ==,iv:SWWfP4mgSk8o8wcazus7jHZOn78cviKuplaRYdWZzbo=,tag:kUulpcdq5pO6SNgCNxNgrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTWJiZVBqRHd5QmZycGc0
            V0hsU3JmclMrTFBhVGoyanhjN2x4d1NlUEI4Ck1BTGJyNm1KVityMXVmOXpmOXpE
            dHR1SHgzZmdINFVNekNEa1pDbDNTTVUKLS0tIGtlcjAwNTc4WTUzU0F0Mk1EeEVp
            dHcrWHpIVUdYQ09yQW45MHlrVWVlNm8K89FAtu1Qjl+8I4ElSGSC9HpBQLpUBo99
            +/gn7LWvRoMkuDAdRFlvPN762FKryFGfIo7S/PEroQXcr4hz1cIfeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-22T00:50:54Z"
    mac: ENC[AES256_GCM,data:V7r9OaBgptWwe6epXeh4lqmHYKVTqOWrvppLtGpZOWmwtHMQGkLTYG0nYCRBzjWt5B/p9h3LHlvEPaS1GxINveOGmSpZcMzloUhvlowfoyyvXv2ngVsULfl1jS4kf7qH8XBlb82ucoYvsY2IgSpEb2VHRtN5/FHlFl979RONAK8=,iv:QZ6NdYe3yJVX+Ffza7nIYSkNcvIXySApjjixYrGzamg=,tag:j0YnCe7miLlk/VQJ0Dubog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
