apiVersion: v1
kind: Secret
metadata:
    name: poetry-django
    namespace: poetry
type: Opaque
stringData:
    DJANGO_SECRET_KEY: ENC[AES256_GCM,data:ftoZNxOCdPrDxGr26JhSZ5KGdJoFFyQosuXcz/7BzEhbn/7DzrDPIH/5fNPl5QaPczNeeJooHKvAiu/3TcCvug/SOV0ig48WH7XZVMp8eJTMmH1GBFg=,iv:cmgm0cY+SleTJbjOgvrdS7jkS6z+nHzBisJ3fXFgRiI=,tag:8cKsMFAWTGvV0JNZfWgMRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdFRBUXFWT0JnRDdhUWY3
            cjlvMWEzOGREUHVBSTMxRm1qcy84a1AvbkZFCllGZTJjSHFTeUVjZnlzS2FtV3cr
            OEZtclE1aHFKNkJXSzh0YkN1NnFtc1kKLS0tIE9MWTBUZ2lWdmhxN09NUHJGbkQv
            RW41cXBpd3dzdEdFNFpHaVBGQUpkU3MK932oojFcs7auZ6JO8AgcDiyw0nqw/Gvm
            Og5nT4HX8ZT46Nd0ioA5LcvEqdpmva4fH8H1Bl23zal0kyXYaYZfDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-22T00:50:54Z"
    mac: ENC[AES256_GCM,data:yL1dQ16UPD4MjVlv0uLzP/h/hgpEDKeI/4bk98Ip+RBzxz3Sl6L9TDpkX6tbxPtCb+27xd27iuodPv/OU8qO1vWiRnpkGKI24YSY9bdex2Sy4j167K+0g9RZoFeT712TngXMdl8N2om4DfA+eoV5Ab6mejva/qnxTA3JEG5P7WI=,iv:LKS+TFaS2bWsvNDY0yYAgkax5BC0NyvugD/mzgAUAEE=,tag:iiiLGD+dPCIwkdEEZQwbOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
