apiVersion: v1
kind: Secret
metadata:
    name: poetry-media
    namespace: poetry
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:JSxejybglygH5WXfIAeSWCSHujA=,iv:vYrlAgG054Sqmd+XB9CRdRun/EXiOJ3N1Zv0kB1sd7w=,tag:PZy2a7oRizxqpKS58bvdXg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:TB468G7zzC6vy/kHpkij3unN1Dk23TAn/ewCfJflqCSG4qBROGXZWAVORA==,iv:ZRq3Ua0pwJmJY09zWbg63EKIxyP+DXBrMCxG4HAeyrs=,tag:E927IspOhQEpEmkBp4BK1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RjdEQlhVRWZXT0llUVdS
            enJTU1Nob1VlK1NNZ21UWXF1MTRGUWxSLzBBCmUxR0NpQUlGKzVVWFlEblBoVklP
            b1B0b1RTcEhZV0VkQkRlemVlQXBsRk0KLS0tIEFIUmdJb1B6UUNBZitXSitKZmZW
            dklBVEV1dS85ZEFEVDRCZXpQeVZtdjAKE4OauriFfOp+AfBZwlvAhm00PExUGlJr
            zzEwJfZ1nJq4S59lwH9F9LOKO0TNjMqBWHKLd99vZWS4i3qSdV4DrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-22T00:50:54Z"
    mac: ENC[AES256_GCM,data:KNQL4A7Z6NFxjEHP4MCJvYsPlHq8Xel52W22v/loylBhnsLGzVlrDqUF0yiCw8ERTRjQ5HyX7Ghg9XDULBuZ3Fwm/FLdEFEhpvmclvalXjET6owwFypcUeBcOiory9Dglx5MrJjJQguVZ/MTOI67EoL4QFvKuIZzIdB3CRl3dK0=,iv:V/PO2Z93uS1sUdRtgmIqS5JmCSJEY35bBtPr/O3yGVU=,tag:K2L2z5o0nKUkZSglQYX/UQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
