apiVersion: v1
kind: Secret
metadata:
    name: regcred
    namespace: poetry
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:4G3cbRvc5z9UCSiiJvzZVE/ljgGtTLvu16w5xcIqJ0oaS/hD+vT1oDLC0OHCxmThgNDyCF2Fv2Z+oGC4C+qSP3JSCxZ54iT0q0uk6kxd8TdbDfMXR6GnI/uHACylB69EYAqmQ3y+olxwegpdS3ODQoRT73JSWP4CRY1xYcj5K1IQCCBMFWzQimEhWcr0qu6XTmE3hNb08/xjKM+8HqCVg5W66ZDKd08CbS+lp9IHsAlgIFgus4K3,iv:ScmSrAhJFdJq4yfUrrBzDMIZCP/60JxVxQZUJ9ba94s=,tag:dzfiviiZxFBnpvmLj2WRpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFR0VVaDVaQlk2YXlNRDhl
            TGZOMm8vMmZkd05qZjNlRE5zNGhNN05MYWpRCkdBWDE1M0dLOEptQXNqc1crQnMr
            QnFPS1A3VlFLelpqY1F3QUdybTduZjQKLS0tIENPcVRqUzFDeG5ZRlV3NGFQNU9V
            SG4wZHg3bGdMNUJoRkdLalZlOGJHdUkKn2nUvg7uQDXJbIcFzb1s0fRORbyDPHjC
            kY9NbXN572bE4LyqMhsoVJVtKrjmZVhQLsBwSI/pjtWkJlzd3aTPhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-22T00:50:54Z"
    mac: ENC[AES256_GCM,data:A8YNVCWEFm0Nbo435qfZ+/FXOpZhwNTmmIZ1fHmxugF7YMaVagBwZGDJ1hkI9uUpmMkwWrG6oVGL+XsWtU7eH8wCS4HgYOOWlemGdCtNcplJJR/RwBRawdTDISpeYxW5p6njl7j1Y8jA1CGk//WzztThD5wiEq3QJzz0MNS6sD0=,iv:kBpdUz5O0gFzV6/4fPdSRC+/dgeUEdPkuKm3V4vBULI=,tag:pnlvEIorTeRlPnjHwh5v7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
