apiVersion: v1
kind: Secret
metadata:
    name: spotify-hot-100-secrets
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:Z13pV/FTi+I1L2Yi1Tu2gggThonUTmzOQRlHgQgJXTCMMCuWzMv0p7+dxz6a2jRR0FmNLNnMDrSzmDdYBz/vCmw5zXIOwJ53eVABf6OYv7qruTqj7yoT/Yxo8SneGoji94ESzYRd8hTsESsyPMJkNM/33j5723bk19wDHtGTLj8wf24QH3IcIjsGlH5erFihRiw790UrDElRCJYvDmilr9SOXrkpC1+Twa7QYGugWg6cA1pC5t/I9AXa8l7SKMTg,iv:HzALxJbhTaAJ+lYJnoMMoqYkiacX2xGi1vEMiWdt4CM=,tag:oXVtS4P0BuZaeQ7QOz7m8w==,type:str]
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:OnSb6Pgkie9akqPMQaDlsyqLUq7snpCQ5JHLlY0jgx8=,iv:QyN3aR/1/1WJ7Wi5OEK7IkVHqanEANGCVu3o1gir/7Y=,tag:DR0eZ04gFzK4Xm5YgH3Ndg==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:FuI1NogSrlyKKZcjpUI7YNNiXdmFGCj5vdfp5ptDACU=,iv:dTvYJH9R0ti9pzSZxB9XOGwyszJ3iFLUNeuE0AP5Dg8=,tag:Nw5CXI0GK8zumPVywyClHQ==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:rpEusNIzP4GwOC69eBiJZle4SicW78xM1DrciK+dAefoCyTrSTghAu3RM0UUfMDZwoSLotmYkiSn/AsM0ggqVg==,iv:7kFFXSQfXdwBWm/XOeHSCrKeSmnUUZjfL0lnxcHHBAc=,tag:zW1VZ8cAMgbEMqwhvS92+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOVdFOWNvdDVTV3ExN2Ez
            aDdjdkM4clcrOGFKclY5VlU3cVJaNnYzUUY4CklmNm1meVkyMVhvSWFIaTYva2p6
            WjBRciswazNEdy9pQmZJRmRxTzdyU3MKLS0tIEJqWTVHMHZjRjlYTmV3NlVFWE0z
            cW1oelpsamhXeE5sRVRveDdUbEo1dFUKuADmWjkocEujs6Hnbe2q+U8YWXm7sU1F
            vLLms0ZE857WvG+4wR8oi88u+OcjiSSjwDfqw5TET+k2iNMzvtDdJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T04:40:42Z"
    mac: ENC[AES256_GCM,data:qohDNq7lnjh6FzfDQGlroOCdbRDVaA1d8nkIAjyKKFfXUMnGuFWnw1NUYgCu4t7ySX7rIaCVbfKNziVuqId3Q6u6ZrVHnkHj/IBbhMNAe3bj0H2YQ2inVWLVdY/3F45MoQz3JROdoZQo33D+YrdFIEKeJPMEn5SxIYQXeIQ5TCs=,iv:eVS98R5tKw15Et1Av1JSI7b7G4djEM7Y/IDKZEbZ0sk=,tag:HXBLg/V2HFMh8O43jYzjnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
