apiVersion: v1
kind: Secret
metadata:
    name: spotify-hot-100-secrets
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:Js3+XVgO3tuOiaxHZZlqYYY4Zlt35knL8qutk2Tdlbhr0QHNtzN6O10l3vZsFlDh3bYb9qtE33VjkIMFrUedPBOavt7Jymk7CSOIT18jGmC0DcYDtetl9kpUehjjuKVCR80Y+ngXn7kjIbSxcL6rGFJEtE/Uz05KzNUbzym+EO9ybZorJj/q/mzdwsSQsKBRdXRzlh1tKPLYYtjS1j+E4YyEpZzdr0popl8=,iv:gPD/N12mo/ZV8Up4vjp+wl8lq0a/YIJ9Ga5OQRh+Dx0=,tag:azd0dYM/3z1nHglVSs1yRw==,type:str]
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:s3MTBms7doWVNG+bAONSZnSZ4b90zpRPHqDuBmKrBDw=,iv:ssGOQmuo3Py16wqkMJE2OrqDdd6cRdFcrrvIaJwlQjo=,tag:M0MTkcifzxmWxPAwCZ1Z9w==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:Lw1Z+wopqo4wKMNQbh4yXkh3zbnws8Ze0ypK1xy5D2s=,iv:bUp1WmVyyaitwxtYtmuYlbs+BxMtoLOQI37KQM9hGX4=,tag:X2KIdAPSbSlU4zCOILIumw==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:dpwCX5JfSTRLfybeiPzpDaZ4I37jmOqRSdI7MRdvwdgkU3XLMti2h2LfVuJjYDpHKCTJzfiXjBGyYq23T92ELw==,iv:I25j09H8DxLqsv+gJtLp7bT5WSJ1G9OWpfkk25zAHiM=,tag:oPtpVmVdWtl77mw4BmjXpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OUd1ZGJtbndpVWpXRWp5
            ak1PZmdkT3ZQZnRWVG9HZVRMMEJkZ2p2bGdjCnZPbVZFKzBvM1U4VTFmR29jUWk5
            NHZqMzBRRndyM0xiOE5xYzhoL0RRU0UKLS0tIGoyUTVQQ3Q4WkVjQXdJSDFzVU1Z
            YTdRT01ENHc4VnN3emd0cTNQQzFhUDQKah38GgVeOcJvHDUmashUC3p9IVgq/Qo/
            V3RSPjexAJE2Ku7elznX2pQ7lId8LG2qBhHpCpAYOsWsGDCB3OO6Ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T01:40:51Z"
    mac: ENC[AES256_GCM,data:NHWmRdj/5OANDqBpDjXHjEat2rOm2o0q++BTNRbJnFwDag0P/c2IusYOet3zX0PEiRQThlsKn+Htp7Wrq/8gqJUZpA30hVbOEHKPZGyJLPqL2aotll//cs0J8WqT6zaZgefg+jyoHD+hbRM0g5wZQLi0NFz8xVq0nff8k+XZ638=,iv:bAxQSFBzJLWax9xCfT/lMr0yhkgU8tmbQmNfFx3AWVc=,tag:e5OoiqxLsjEiN7R5+vKKyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
