apiVersion: v1
kind: Secret
metadata:
    name: spotify-hot-100-secrets
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:Z13pV/FTi+I1L2Yi1Tu2gggThonUTmzOQRlHgQgJXTCMMCuWzMv0p7+dxz6a2jRR0FmNLNnMDrSzmDdYBz/vCmw5zXIOwJ53eVABf6OYv7qruTqj7yoT/Yxo8SneGoji94ESzYRd8hTsESsyPMJkNM/33j5723bk19wDHtGTLj8wf24QH3IcIjsGlH5erFihRiw790UrDElRCJYvDmilr9SOXrkpC1+Twa7QYGugWg6cA1pC5t/I9AXa8l7SKMTg,iv:HzALxJbhTaAJ+lYJnoMMoqYkiacX2xGi1vEMiWdt4CM=,tag:oXVtS4P0BuZaeQ7QOz7m8w==,type:str]
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:kfua9iEx/Gy3tfyyP23wcBj/JpZlWs7vTo3bHmXgvuA=,iv:7zGpNPGDrHiNmsNoDWqqs8HjxntaD6y3tnkBg00HNIY=,tag:hZzEpv4ozdJWTBasO9wxwA==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:gof6VgIt/EIvbqk3bl+1VXYx+wuYDKX+B8avThoSPjA=,iv:FoT4qbEeRgK84Eh9CzzvQdsdYKAoIot9HXEdihxKIV4=,tag:q0mSsRL1V0rdzHFuubQp1w==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:rpEusNIzP4GwOC69eBiJZle4SicW78xM1DrciK+dAefoCyTrSTghAu3RM0UUfMDZwoSLotmYkiSn/AsM0ggqVg==,iv:7kFFXSQfXdwBWm/XOeHSCrKeSmnUUZjfL0lnxcHHBAc=,tag:zW1VZ8cAMgbEMqwhvS92+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOVdFOWNvdDVTV3ExN2Ez
            aDdjdkM4clcrOGFKclY5VlU3cVJaNnYzUUY4CklmNm1meVkyMVhvSWFIaTYva2p6
            WjBRciswazNEdy9pQmZJRmRxTzdyU3MKLS0tIEJqWTVHMHZjRjlYTmV3NlVFWE0z
            cW1oelpsamhXeE5sRVRveDdUbEo1dFUKuADmWjkocEujs6Hnbe2q+U8YWXm7sU1F
            vLLms0ZE857WvG+4wR8oi88u+OcjiSSjwDfqw5TET+k2iNMzvtDdJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T02:05:51Z"
    mac: ENC[AES256_GCM,data:BaYqCG5UIlgiBmwcjCoSDKcjYuypI2cCyMlMloXrn+2L91NNh3TRisZHdmdA/8pJLrpw1Om3ogK7ktN7+2h7T/ymcFKajcXzzw+OEJ12b2zzh2Zx2gPn237FkpuXCxnUUDU1CpOH56V0uV/XJI/KJ1F/kV1n6IOZYaaTwnAeNPU=,iv:QkN3rGK4njvQNrji821S0snhqQhLCuydJd76JR3kJ2E=,tag:KdjsfsohdE5qf4Qb59w7xw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
