apiVersion: v1
kind: Secret
metadata:
    name: agent-control-plane-hermes-mctx
    namespace: agent-control-plane
type: Opaque
stringData:
    AGENT_PLATFORM_MCP_TRUSTED_CONTEXT_HMAC_SECONDARY_SECRET: ENC[AES256_GCM,data:qoeuP8EfxEmHcd380A2TW//c6tpAhaLymQdGOh0iNACvIILbQE1abLk94GJjzDjWKpzJsqvzbgn/lIq89JjkAQ==,iv:57ggkWryEiS6AuJ7SC+iplcNz3KMmpGnWp0flIJHCyI=,tag:yrVbW+e8x1atnVzdZdum2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdzhMbUxTMDNZSDJ1NVFj
            dDNkTG5pMVFGV041K0wraCtzTnc3UUk2cXlBCnNFdElwaFFNVzdOTXhtWDNmSVBQ
            UWtxZGRCZERkOFJMZHNDTUdjT05salUKLS0tIHJoY1VkY3NZeXRnVDdLNDJFOCsy
            d2FvUTJWOGc2ZHJQQTZDcFBYRS9URnMKMP5i5JpNcaHuXthWSoQneDXlzLrXakOS
            XJu30JD1gljLXpUVIP/9vHApOau6C2edAlbapDBNNQNKXR61ZOI9sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-05T08:25:42Z"
    mac: ENC[AES256_GCM,data:BPK+HzWsuiClbK1iERgW4PAPZUIJfbZBgG5IJLciZf8hc2VyHxeQUl+mJLfLthBe3aVO0npHeFqQbXq8iUGwIfen9uEuS/7JP8z3/4lyepH2be1EC7VLnL863opzl66VsFb4T5aY2AcIfOGP0qmCBKCVwjuxwPQWAE0a+9ExBCo=,iv:izcXrpCHCYTKrhpgz+B60Z18RwkOl5gF+N9KyTQNMw4=,tag:vE/epYSSu00AGCDlBJYPKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
