apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: agent-control-plane-secrets
files:
  - citrus-dev-broker-client-tls.enc.yaml
  - runtime-secret.enc.yaml
  - hermes-mctx-secret.enc.yaml
  - regcred.enc.yaml
