apiVersion: v1
kind: Secret
metadata:
    name: regcred
    namespace: agent-control-plane
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:XaptgiT+y3+DzS46RgsmpxhdHMvB/gIu3zZtNIGiEI2u67t4YLHTgXr+EdeZqRi+/g6wMZAvp/BW1mFizmbuc1Ddrh74yv0+diVYdyNZyvOGJOVAcxRyeGk+vZhXeiKYZKQOMehCy9zQuL28CEeJvNoyLW+sBqX6ehlFyIDgqUduVCJqiPM3il9x0kr1kRF+ckSXrH+GRwVvC3zQmub1rYJ2u2pzsA3RssTvm5Px7p/1Ie1/ONzYkUSP0akpp+zewxKV8wI9kfjGKFMmHIGAYqc1gxbYmZ18QYrIJF+BAIF9k6kk79ikjuwuceT+T/4bXO+DsjLiAMmlljhS0qhCpvcaRqy3NmufyVzgn3+30uMKGVHaqsqjYKI+Kw4Y5Mn75MNZLsaA5hRz3MFXW4GFAncIrUGF4y0n2qf3bAeLupVWG3lZsGKhkyazfSVEAWoFicZwss8vYt6tFuiYPGgExfgDm94Nl8hVjVbDtSqgRWA0+eqA9fY0spAxQDppcKHiHBTf1t5Cs5E8rn3d3zNfU7MboJeEVOBZW+taxqFavumjcnkEr0KG3iIkaxPgIo6bfJejMJFPmqXBiwD5yeafj/5g4M8+8kZzVwZxf8fNuiOg6x3AYie7hEKLGBmmrScVrBCRTDdUv46+hxjesiVJcIu6gE/doJlbtxfpfQxpfUZn5gnLER0RvQWn77QKe6y7uAXA9yW0TQTkqNNF5vguR755YmguLUic,iv:FDX7wXIM3XGr+AGYn7FGltsjGKhWai2RcXUcSNaJV4U=,tag:PRSTGKtNYh13tHsUUlmHuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NzBSdjFxQXd6TWc4ZUxh
            UCtQTVFQSGxuMHYvWkhQS2x6Q28yanVyQXpjCmZmN20wOFp4Slo2WFNVMEFZcTNp
            TkpPVmZXU2pJYXlTNDNrdGRDdHdycFkKLS0tIFBlYUZZUVFSVENhZnFnK3ExeEVt
            ZGhwenE2MWYxdStETnY2NDIxb2xVbFEK1NIGz0dxq8eE7xvJBGpn14d4DvFkSJS6
            ri38VrbRtUeRFURES9GBJOWpZR8ry5spfYnzt8FFQVKlrACczdt4NQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T07:07:13Z"
    mac: ENC[AES256_GCM,data:H0tPAlqLN5sGBRVGwPzWGZeBl3jSlbm1ruz/1jdhUK4qmdv/Lnlpmq5RsChPypuDdIOdauBi9JAdIliCU73cdW1eZYBQJ3VCPMvqStPaphdfLRGskeT2G3FP0YiuGV3gJgBdxLCSS8r53zXqItro0o6wyArCszWRa+MAg+UK7/M=,iv:aFaAtY5Dp/o52FudcMbAjSsruJgw2ddKkYeZcK34+V8=,tag:7tq3uxJWFBHpFrq95dHUxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
