apiVersion: v1
kind: Secret
metadata:
    name: regcred
    namespace: agent-control-plane
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:60TGfJ8n3DBFqRYoGk2NUY6lX3+5Sa7VUnNpdjz5GDh1A1GgsV8k7EOcW2Bnk6eb0cgC3coB+bLBKeJfsHej1UPXR/aE3t06yksDyUdoX+GO5ICYDcofg3PQmT5Dkk6zVWOSpNl7xXG4B4D9pt5CHs2fC8LWVQqsce9wU4wHp41foX5ZoxSqZT8tzBuxI5LR2dT/d2KEuMyrRL9mBZs/gR5sAjeyXtMIBg1bQ2aHaVR3sy7yssLaI98x3YhxQzxCDKY73S0mPwBccLGSf0+EnkodW1FivQWSjyacHP8Y1o9r8JuR0NP1v3fmYrXavMBpEzhS+yIzgEK8i5zPMdhfncovFrwjoWGsXlQNIW30udq/zQOokWvB+aL+xV/Be1G6ATo9kEHMDGFbho8NH1TROZBHbErMq+PpKnBnmdyY6w7Mw2i5XgmeUJKy+ekkdihA0X7B4+YC8FLWzFplbZKIoaYmXGLZ8oSTPpmWt/OSP+I3dEN60BlkGfjH8l9tg9tnTXeThTvd5+lctaZT9nc1h7ble2HBX1RhqpWntTLt/AYk1903haYFyNAhtOi3qlLS+ps/twIFQvt5C/jw1EfUsdhobTeLrn1lY8f7EDJxzA6wvCwyuJbdiGK5vcOUTaPjJucAA2A9aQqkKmGkBZsm+pQ7VA/zmaV3fXkCJewjIEsWpWRNTmvOXLiZbptEWDkzP10Saa7O2dgKXFfV3YgoTMWISAl04JLg,iv:3fXQI3e2hGgTYetHz3+x77Fc7dk78ck7sT9eplXQvxI=,tag:z/Ds+FemWJdQ/Qb/llSMNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGL2o4WkpOdFE2T1BYRVpK
            SlpkVFIyM2l4eFk5QjNCa2ExM051R2JIOXk4CloxYlZpenhiZjBMY0hMaDlZV0pC
            M2RnTmVZR1hldnVmUDZQazMvZy9GU0UKLS0tIHBSc3lwOFVGWjJCczNwcHpIbFE0
            UVZNeFFVK1FqeGZXY2RhM0R1TlkyeW8K5BFm8V3BjZHpk1kOTTzNhJY1eKswEDpP
            Pp+Kg/xb6DUZ4igc6XBJFvCg1pBt7i0zaptN6qNZsKL8dbOETzd/gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T06:59:14Z"
    mac: ENC[AES256_GCM,data:A4YLVhkzkijoOrtByaF5wp/CtOnGFfDJF0ZTL3b0mqmboySsnfENnLO7S55sr7QAzc5Zzdj777Jv3RV//nvv3A2FCxWCTATWr83bvAmVDzywTLQbew/555SXCYT601Ben7ZKVo4W3cPzCYmOyuaHg7P5+L8Jk6/GIGF2lxVEggU=,iv:SRkp6hxCJA/GXN/fKn5/B+IPl7yHhc3SPLbWjm1cNLY=,tag:Pg4+6fg3LADr4NrVBxygUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
