apiVersion: v1
kind: Secret
metadata:
    name: regcred
    namespace: agent-control-plane
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:5evcvWOnkM0B3TZ11JnbTjkwI/HvWQYofzaTu0Dr84ASvt6pjoo72W2vjUbC6Jttepu0nsvEL08/e6vY2nCO2zgj+nGinoC5N/dijC0nRN3xf+uqkamCOntD1UAXQdw2Uo8gQc0HFmuwH4mtvZ/yTh1wDTfCDzUit3Qv+K4up69tA0QOyu6gACWCT/gBLf73i91LnJAok9LVp0DV60JqDq5Tm2V09OU7PVyIvpsV2uFX305ngv8f7/Got0zMq5NUbbrikL4t0KC/7MR503TKDIFshM09c+jnv0Ris7KfJjVrKd7h4DnoNlm9hFC2gVnIT4kJ6+Pb0wTzfqp65y/FFMjUL45xgvjRE+gQmaAS7YJG8FyEiSNxU0hLOFn+llx3LkE2e4P6Mko076cg6KYrEDNUW50FF0lsDwLfpfZiK9d3hji+nRHWZRFXCqVkA++PzgQspi9Jp9xAmNw3it5Dqfv+S/FTOXVTyxOG83eRGdMadaYDClQrHtEExALgncw7EaZG8roxcI+Rkjfsyi07mhYGWabWVNnWBzZqynUbrYFdiEo1tVxe5ktKuyZWKP5jqucSIo8a+eNL0ZgdzfGjC3RMOrvazb5feoaCL78t7Q0JWYtAzktIro5ILbbuVZr9XiyP/nY93bsfGqF6Tnn4aJTNGONPQ+ECPbWitKUefAFCaAJsl5Aeyb2S8IKP1IaDQqbk7wKRyckMairKlVUK5VhOfNo4YkQc5DpwchFgGLUvfsvcPqodLstxMwarHZTKOXSDvJT2WsOWCpAP,iv:P/Oc62T0UjYtakP183cT/RXGgLQF0GJxpVAPuXSgtA4=,tag:NZdgnirzb9vVqwbC3MpjJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBET1gxNlRBZ0h1dTFBR1dX
            NjdlMXk3U253OEY0YTdVUTdvS1o5S0tzRWhJCjhhVXJhM2YxK2VhMzFsc2xubFhB
            ZmQ2bUJ5MTVPaUllUkhQcUpRYnJzWVUKLS0tIG9veEI2UmRiczQ1anhuZVZQc3A1
            dllGZzJiZEFIZlYxQXZ4bkxBL2hYdGsKs++TKTKh0ZfxhKiwUlUv67ner/e4m90n
            gStfK0EHSvBLEm5eCD8Z2a6dvl0u3pMZaAuqQOFlaMQI0cAsF9FLbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T07:20:41Z"
    mac: ENC[AES256_GCM,data:nvL5uBc+iwuFyn6ko7M3NEHwG/R6MLd6IsGLrm82NOMv8P9PBdwmdbK64nfIJNrhkyI19IGt0yU5sMiiOUopVIgwUQ6N+ie1Y402lQYVJXQrd6I/udi1Lc1mW5qgeiE6lRuKiz67fEWYQiZDbgQoayOzPq9MT50Iue4dg2mm36c=,iv:Ej5JnlrZljXN3ly+MUjiUn1ObFLV6CO/ad70wAQrvug=,tag:du0Tywdifjs77TSBd4VWFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
