apiVersion: v1
kind: Secret
metadata:
    name: agent-control-plane-secrets
    namespace: agent-control-plane
stringData:
    AGENT_PLATFORM_DATABASE_URL: ENC[AES256_GCM,data:KEObJnaspKYJUzY1yDD3kal0SlxaZOR3sk1y5j5xj229D+yI/0LA2eMQxvzJ5/K06qftAMnPJg8gyPmFppzI+HkU35fkU4787mGxLor2e3ykGDh5y4/H6uB/zOeQP+r9WV3fbc6dOPVwk48YVlgfYcFOfZwsDf5CMkiJ5BVu+ZrApADvOUmfIKApCVFbq0rrRLL9YG29rMklKm3fGW8DiFJsIwhLZxLpEyYF7GkQaKQEUYEaQgyddw==,iv:F7mNIxlab8N+qgo4DvFPb2EwVZcnEgABAjJs60UlwTE=,tag:Fda6m8xctpB06Vdfgo+GHg==,type:str]
    AGENT_PLATFORM_OPENCLAW_TOKEN: ENC[AES256_GCM,data:nTnFAZaYpT3FCMYrzzkO4c3KXJAquRBt1klE4Me9JQ5zgz/4r5RbKJRqo0EU1zDWa/YYC5zSVnCrYjVl8Fidug==,iv:YwIY8lZu2BbimH+Krju1WcX+kahswMVPvurKh9RGJ8s=,tag:GswJXB2OrBq6T0K3p+jPMg==,type:str]
    AGENT_PLATFORM_INTERNAL_WORKER_TOKEN: ENC[AES256_GCM,data:o6ze0fpnazM8i3/1OubwwOKz1KQQ977gRnMOQwTjyiIxKB8MwGz73CO2wSrPx0FCUVKK/cWlxS8i8PVVfYz8zw==,iv:pTdkreYO6jxQa1pmTNPpuNdHKKLB6VyIhlGcQcZSlps=,tag:p2WikaNNDX2P7eRwkZr3Sg==,type:str]
    AGENT_PLATFORM_APPROVAL_TOKEN: ENC[AES256_GCM,data:POLi/rsSRO09xobSatGX6t80N1gRZ1SWSzZhsW0xxCbm2kxvQDrFHhg3eao490qBrqa/76ug39iCkCZNdSunWQ==,iv:gqY9AXptbXTTWPCcBTo6W2DLE/wEuN2Uj218LIC09nM=,tag:COvEjdfjge3VL1sZzljHJg==,type:str]
    AGENT_PLATFORM_AUDIT_READ_TOKEN: ENC[AES256_GCM,data:XPuLNpJIzZAarf7k7OjNQ6WPpZesxhc+2ommoi8iFXVf4Y3WPOjzj2ALSKcRwWMnx5ZdY6Er16ZJrQhxy6nb/A==,iv:xX6bHL8+3iIs3FiGqGs5/+jkEDoe3hcLuNzQqndOMJM=,tag:GKOYKrTXoJDIqxQDix3Dew==,type:str]
    AGENT_PLATFORM_AUDIT_WRITE_TOKEN: ENC[AES256_GCM,data:pNErl7PKmI30gJjAh7LzzZKTaCZ8qZEdjCnVTW+IrZyqr5lHedpI+DYEvJnND4FQR9SClIFbMW1WVDcRWW6eTg==,iv:54NvRePIcrhnN6N2QbCDgvIVOTcmkEtZyBxzKBSrviU=,tag:ZIumfB28rEHjBDSAyAF4Vg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHd29ZdVI4TEV3bGdYbTdR
            bDZ0OVc4dEtmMzV5dmRxMHczd1ZwRlNVVWpnClJIclVUZ0dTejdERTlYbXFReEpG
            U1JXbGtrRFdYUS9OWndKdTVkU0tZYU0KLS0tIG5SYVowRTRWZ0RLMXJEd0JQdkFK
            QktGMGQ0bC9WSVFDK2xzcVhIZUJwdGcKuwmCRmkwRfKWpcIjMzSB7yyXbxefnKdY
            wRxBGlZwDJtp9DBcy2IUbHQfNrPAUtbm4KKVbxDZDoIyNFJzdrp7Hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T06:59:14Z"
    mac: ENC[AES256_GCM,data:ZEK+3pEBkErsUaHNtJhqN9lU3e90d1cve8PRY5Rwz88LCD0YBtx/+yXBSfOx8Zj+KZ3lo8Y4mVHfw1VEjIfp7gi3Vj1lmKBDC1QVorxThqmknVcXBMZ1SaM4b+1ihK3v3tN6eNNcIoAhyCi37gqCzEsMwqt619NY7vo1hWb8G5Q=,iv:Pzpfu0mBkr6MTSmGpDBFnuKwbnBM5cYgxMvySwk0nfY=,tag:6qrsNkgIbxfF9ToGtG4tIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
