apiVersion: v1
kind: Secret
metadata:
    name: agent-control-plane-secrets
    namespace: agent-control-plane
stringData:
    AGENT_PLATFORM_DATABASE_URL: ENC[AES256_GCM,data:WMFsjTJGWUMchDrmTSg4QeIndgt8+b6r25VKFHNVq1X46Z8+18Xk6907nqzcbEgZHjBp+BX/VtCvexOEGZXmMILHbEfWQIx62WtqGN3+K0ajrqLE+deLvphG925o+lvOVSiO63L2v2cSdH7iE1M7ZkhLq/nGJ8k9IpVdQJoc4pfJ2nw1RLRgrcgkSYJPWMUgNRP0Ff1Knj8pEsZb+6QWyviEzAxzx9wE9yiDEX/uIeWHEvUBEYGNSg==,iv:uNGd2Xp/0bM4Zq1YRT7RsSPDQG4GoW251jqLl/r0yVc=,tag:fqo+LF3D+Y6SWvn3nxHqjA==,type:str]
    AGENT_PLATFORM_OPENCLAW_TOKEN: ENC[AES256_GCM,data:YO/LDt8hr0Z78nML9aydOuyTa35uBNiIjtxL2eXZAyiA4pEYsz2x5wqiwtHBSHSOxaBXqKhrGoZ9Ge001PPFuA==,iv:X+6PDE2MBCWn+6bjuxT/u451+jS+BAcDO/MqkLh4Y2k=,tag:iDooFGKI4O5tnMat2TD7Ow==,type:str]
    AGENT_PLATFORM_INTERNAL_WORKER_TOKEN: ENC[AES256_GCM,data:5jt+/++MaPEUz0eMhLs6MfGtYpc1ooj66KfbEjC/QmubMZtn0pViva+GcpLDwGuFThNkphimj501jbD+LOQkGg==,iv:ZgMhGpBzXwlphstVCknoq0aixhjGRbSouxhTUlSPhXE=,tag:1K4/P14S7wfXbcy4pK5DbA==,type:str]
    AGENT_PLATFORM_APPROVAL_TOKEN: ENC[AES256_GCM,data:7rNg5dKrPDVA6mBbDkPkNwT+lv/SxvnOknFturiKkQcsb4iaYnHuMxvkYT1Y0eQ3zQcp+ev2SLwnv8SXMaTVfQ==,iv:xrS+syx0qTQYZOZuryoKEVlgERBEF5IoMArYMa+/DE4=,tag:fkAIBon7zlTtJYt52shNxA==,type:str]
    AGENT_PLATFORM_AUDIT_READ_TOKEN: ENC[AES256_GCM,data:tNKbqti60wfOE1qz1iCfm8bmBLYBFHX0VtLz4dmSAwkfHEnoIa29pkGpyhNmtT2yi/fH0CLjUfVQcHB1taK8Wg==,iv:Zri1KMGj7PXprzr4C3NbnvnsvbobwdFC56GxhhtJlgs=,tag:VpXDxip2KoVMBoLe+XLREQ==,type:str]
    AGENT_PLATFORM_AUDIT_WRITE_TOKEN: ENC[AES256_GCM,data:aime+lfBPBf2Q/mXOfyf9enqjBFkCDPMb5vetf8nEqgMaLkZBsF/VQsFzOlwqxxq4d1S4Gs+uM2uQ2a5o34/Rw==,iv:+FJYLMRmc6SEhAwNLw6R+BgQPg1axNtqse7ZzXLc43I=,tag:rXuWANWXTJuAb+Jn0h8h+A==,type:str]
    AGENT_PLATFORM_DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:xYsC8hgEwFDoyvzbldIVAiscQlRKTdxGST3j38VBS9VBE02DQ1YUht//aAelb0DEkKWE6LznrgfsCsz5xGbTzrtCWfdHwq3V,iv:ZE57WqoVJz0bAbx331A87Np720ndOK6nTlApHbFP9b4=,tag:9LhtblwFnISJIqqzoi5Ueg==,type:str]
    AGENT_PLATFORM_READONLY_SQL_DATABASE_URL: ENC[AES256_GCM,data:9sxGUjmHfOgo23C6fdxhXjx33hdOQNnq2gPzYJ4tYIg4NGEvQiObE6zE6Sxw1+DTjXArhhnh5Q+n4w+qIQqrCZ0nu3VzlEMzUiJoszGaZe2YLpuoYu15NKr0VXffx8nsXjOEZyEm9R/ojdKJVN9PaE8u9v0asIJeYNc79T1CJMYGFKaCeTnaZ9cq9inYNHTH04zXEa1v2tgb5cHuHZm2jjrClGaVqrmFU4MPGGFF52qu3bJ7IGFAAcY421BxueHK,iv:HnNnh3PtGlzsgQ7Q5wtGpbUYsIk/zL/jOcDE7gbjwQI=,tag:bpiapsdwcWzjmDLWGe1r3Q==,type:str]
    AGENT_PLATFORM_WORKER_SERVICE_TOKEN: ENC[AES256_GCM,data:n4gLWrWCq8To7qF442pTCoIJjrgGvy6msldQ0YvsKtglzdJXYI+yT4vi3TuOEx3G58Wd+DJ0c0rvskSA1kZC3Q==,iv:FOqazv3Gi2ynXW9i4p4PFFruJcjoUyOlVOCUFdBxEs0=,tag:h68SdK4n4NfVhspbCI5v/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcmVpZ2JSZUpEUDJibWFa
            UmFORklsbTVwelJ4Ly9uVmtIbjNObnEvVTJFClhBamVyM3N6aWZLMzV5YnFyQmJV
            QnZMN1hGaWErS253bkVJOFFRNTVablUKLS0tIFVuUTMrcCtuTTI3dEZBVFJYR1RF
            WTgwd0h3WVFtYnRzakpGMXB3QnNUc0EKv5ZUnTk2Z1tJAm6wtLMXS3BWuk2cjJPN
            cGK9vKRMMs4J9VMJSGzuhS2eWqcsmmdDQlELQUJWuHwCcyoP5/SONQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T02:59:21Z"
    mac: ENC[AES256_GCM,data:k8qqm/ZJW61+NivQo095UJgqGGPAvgajcKNK38YZK46sdP2YXOkr11pn8+5GjZLE+miSqvJChZMJmkDO0w4/TgcZadtVwt5yTXHVrtMWyXPjFgu5Daa5DCF/cNRmiP4TfiTCshy7FZTkT02IpLEzhV56PuqpzMSupWKvSVJOqZs=,iv:lIi4PFbvVU4+3zM+PepgS92abpxt2sgEgAy4gzBBXMY=,tag:reedQJhF7S6r8pXfOEQaHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
