apiVersion: v1
kind: Secret
metadata:
    name: agent-control-plane-secrets
    namespace: agent-control-plane
stringData:
    AGENT_PLATFORM_DATABASE_URL: ENC[AES256_GCM,data:/SyqyPiFuVMVJpVrSC66pFEGZ3GqomoyL6GEEH4nBWbqafYn0IQIm4/xgaDf7VxxYf2toae1Mz0FI2qTCkgOMguWf16vc6yKhhWIZaew+hiFeu1+pifp+edYVuIh/tlaz0x+Q3uSfKTxBv6XqdOoUT/BjOkPyHrMYPF2yRJblnPXmGc3puFBXJwi2MKIBU08slH4iCuF2sOJ+25g+1PUppe0SiHZ39lhXtWCiFKBclNybSRbkT6v8Q==,iv:dwugNMWwK87VqYN1sUJ2bWQTS0ivdt41Fb5yVuIx30U=,tag:bt+N5uNVfGgg/Hr0NsM83w==,type:str]
    AGENT_PLATFORM_OPENCLAW_TOKEN: ENC[AES256_GCM,data:1J7vawOG+huN0fwUJ+PwOfl79+PcB9mqfXXJzmz0W2rWOPlKi0sAWgsdpyefUTbQxxTWWcge0mUQX9l31O6nQQ==,iv:GwvNGt3HdK2s/vV5iNTvKzqYy2IO97goRAHL0G8Ewag=,tag:axSpV2rTZ6I7bgi+CbbEWg==,type:str]
    AGENT_PLATFORM_INTERNAL_WORKER_TOKEN: ENC[AES256_GCM,data:i5oVCu4wzejg1KYdUr+dtN/a4z8Xr+TL7tOnybXCpVj2MsSO1UWGlyRjpmHMAJYJIYcKklsfo3oRmuEBCdriAQ==,iv:biZPOuGsoT58PdT0O8o8WKyJtJTEt0/Mg1wSVlXwGYE=,tag:vAudUVVKD5wVJ55/VJtUbw==,type:str]
    AGENT_PLATFORM_APPROVAL_TOKEN: ENC[AES256_GCM,data:KgmFbQl54yXtSzpwbq/+Mz8h6wgmJxkpu+vqAJW7Tsjhv7lSwKsoSb9CoQuHA1VP5kOCGEhDSwGXjfjmpXeBvQ==,iv:jnOtzGrZc5PNHnzIaF+noPnOYy1Lt6Y8dYj+cKeTbKs=,tag:ihyVLq3Md8J6jDvJgsBrDw==,type:str]
    AGENT_PLATFORM_AUDIT_READ_TOKEN: ENC[AES256_GCM,data:PTi0Snwia2WyrTK8Hbi7bgXnW5iwtoxB9sNYQdc8HB3Hf/XkcXOGLKC1S+GkTh64LJPsQJ44+l+tj8T9kNKpKw==,iv:gKc4j7GDt9SmLvpTpyLGTuHpy0kF1IzCb7VD4FxsLNk=,tag:SI8wPnoEZI8d1hPSL/Pmlg==,type:str]
    AGENT_PLATFORM_AUDIT_WRITE_TOKEN: ENC[AES256_GCM,data:5eV6dfltfu+7GfD+slMX7HXM2VB1fjC2JTeSYBEH+WZ+n0tqyGl1e6/B6mjCRRvAze1mPPm8v0Z500GOKQkSrQ==,iv:8hepFR6VfQyTQyFPLgt1AgchonP5VI1L+g5U8r1uzBw=,tag:aJ36XvJEurnaSRGulWRvVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRThZVUJYNTFudTJvV1hw
            aXBHM2JrSzFoWGhGZk8zQ2tBalpvejY1UldjCnkyMTJHTWFTOE4xNUpPOVJCdDVr
            SUtsaXA4QXJTZXBWeElqOFJMNXRDRUkKLS0tIEhWazBWYnJhNFVocU5TZ1FIRWJQ
            MnBERFpTV0VjR0FGRnJDTDVlSDNvTVkKTwkboCY2z5qXD+bFLf3MDNJHeHs7obkQ
            OAfVpND4UrFcx7EzAsnrqPdVarckatiue78LYSxcaJzxOCRJ0P2D9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T07:07:13Z"
    mac: ENC[AES256_GCM,data:zcZXRrk4txTat5glC90sHQCGweN+FD/mlnt3PsTsatg4rW60YaJT2bvD85jDvaMBkmCdpFaiLrPEYQmhpfQUTlNxZCIQWdz0h2MX1Qd015yRnE5hqt7b9tgakwP4E3hqxYqh0ZNRyPVJh1OE9KFHXZ2Ny4bkcZLbexsHUS/ebXo=,iv:IbUXx2ISo1E+VL57fZPGtl/ryKpBmBqH28I7FP2ym+8=,tag:6MbptuyeiM+kHauumwSGag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
