{{- if and .Values.ingress.enabled .Values.ingress.tls.enabled (default false .Values.ingress.tls.certificate.enabled) }}
{{- $dnsNames := .Values.ingress.tls.certificate.dnsNames | default (list) -}}
{{- if eq (len $dnsNames) 0 -}}
{{- range .Values.ingress.hosts -}}
{{- if .host -}}
{{- $dnsNames = append $dnsNames .host -}}
{{- end -}}
{{- end -}}
{{- end }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "splatvote.fullname" . }}-tls
  labels:
    {{- include "splatvote.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.ingress.tls.secretName }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  {{- if gt (len $dnsNames) 0 }}
  dnsNames:
    {{- range $dnsNames }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
{{- end }}
