apiVersion: v1
kind: Secret
metadata:
    name: agent-platform-repository
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
stringData:
    type: ENC[AES256_GCM,data:SZNA,iv:hSyKY0DSS0jrrG4TlvqZJGnlSPcK4ZKhMnt+8/9blMo=,tag:qTX/JhzAbM74zutKZ1q/Ig==,type:str]
    url: ENC[AES256_GCM,data:eB/gtcRUgTRp7MSlGdncfGsZ2UmxCW0i77kodZVY93oMP57lM0Qx/I2UaXDy,iv:hc3HO6E8Qzp4pcW3rP5buo1HufRVFM1GkCijcQBV+74=,tag:dyOG5LG+6Ce6tEWUzrqsTQ==,type:str]
    sshPrivateKey: ENC[AES256_GCM,data:0OxVoeadWdqlV6GWiIrAh9wqgXu8b1mdehW9lmOZnN6lpuUjcpw5uRRBp+py+tazM1Hjjpiiwo/OvjKJroI3oJq9uuAOXGOPva2QTwqq552qEBulBPhZBQyUlhYmckxwmbmI7JXy/nerW7adaX3wEXBhP2XyzhYMpbTYD3xVMYQE1/DYBBkrh3puLGshmh8AcVQjegS5d52L0KQmB2DRIpS0eSM60jA9h9Mg8T2ArtRPYsjZOoTRA3b/eq1tG0I6v2/rutQxvNVShBI7AS9S6Pf9JGb4Qg6TJFd+3OUkZFwgtIygtSRgwr4nuJEgwKYQTKNRj1kzojWrMdlLoMNeTSpODWB/+8nyoK5mGQ0/MwpzywRyq7KUbUlA3X0HRDKeK+XMet+J743ZtM2CEw0HA8WNpFR+WDIWKpLlWbVO3yXQlXMcjYFYuOansy01rj4eK00Nk5CapsQcN6eVijuK5eWDcU7qNkdU37tiAOinwgTm6PlhA09fZAgKtEwy0sZqdtw70gLQrWCL4BXoaG+FRW2jIvvIooBgha9H,iv:rncdQjwQZ725BV54mC+TEUuwrdCHJYv6fRfZgcrG+bU=,tag:ZbXnnjBQevV3aXpXy9VOfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQ3JHS1J6cjdSSE13dklZ
            a1VFb0J2VzBoWjFTeE5TM2hSRXI4VlhrcFdZCnNpU3JaTFFGRXpNYm5DOTUyWHc1
            TUgxWmNVbEExZ20zdjdqRCsyUEpMbncKLS0tIDU0YmwvRFgzSjhRaGVEMEwveUJY
            RzB2ODJua0orTjhEKzhDOURvaEVEQ0EK/zK4oz9Y9UVtZYexjztYOyqIQd0S8720
            j4zudPiqjrq9yMAKHDqgJPwPAqF3We0U4rwPcUuop44XVlKlJpBzXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T07:15:14Z"
    mac: ENC[AES256_GCM,data:mBwlpddzGLoThBhX0KCvHcx9BKr1bCcyCHkco7ey1ehkiBAopNWkl9iC7kJrN+WbuBzmR5aCxpupWAiQdqUFhNjg6fRhO2X9fxQNzLWOq1HMJ9Jlpdr/T1dfgh2Id6lu2M/6RePf4tsZ/Wc0UmHe2M811CbZhOPW3DpgcpuJYmQ=,iv:XE0Fj3rFuxmiaro185ZgPoLckMcegWR/jWqy6kqVJU0=,tag:0huwtb52iSo2kYJ+RFYaZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
