apiVersion: v1
kind: Secret
metadata:
    name: bot-db-readonly
    namespace: splattop-bot-agent-8s-dev
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:ZD/YsaggjVeWGL0ixbWvZGsYQ3D6zo5tJzewVyaR5oTgJ5aGx/fFgBDHi96I72LmXle9BBDm0BhOgDrEsbbxCMD2xoxONdPNs75TGWBjuE8hDCF31YLOUZY7vahmWBNiugVOAXpdDrKOrevBB1mbmY9U4eTYdvgpuxr9m2UdHO+3kB79VBsCMApnR+0IVnakKWVDxCaWjRkNfcuweHnCzV5Hk4kIWMF55AjR5h4tNf9XUw==,iv:0+gK4PCgH3aibIotmkYfqNXkkRpae92aSMh4FHQnQ0w=,tag:/Vb6VGOBuRJJe2Y/y+OZHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTmZ4L2pWOUNwZy9JSGt2
            QzlYaW5KU1ExbVR3bkJLVFV6dXZkZVJVRG5ZClI5VTdEZU5jOVFicUdjUzl1MUtK
            dzcwK2ZsMUdJWTV4NU0reHNnK1p1SUkKLS0tIGRzY2ZaVUM4VzJnMVJ6UjNxdmcv
            MVlweXREU3FwNDNsNkpwU2ZPdFRZekEK1vrKnXOw5eAWxmJd1ASp6tU7yU2MeFo8
            Q3UGCmqNgEKrguKMIsGM4ShaqjMhV7BqaYgt/hHAzoMaXKVSYHFeyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T03:39:26Z"
    mac: ENC[AES256_GCM,data:vJbUds7MkR2qeacRtw82KBJb3BelfHy8DaTEVw/T3F3UofLDZr8Y1XluJ5We0M+zUE1bY0ScyGq62G3pOqa70g2BxY4K+8JtsYdX95myrH4JldhbvmDgnXlfrs+fx6L1uWhOFwE7lvbT17/eqtSO5IQ17LWzck9TDFWOmkoP7iA=,iv:XQy4nUXj84uYRn+Pkj1xyJFSBB6Il4+BnOIdmz3fwI8=,tag:ccwk0y3dkWJ1qxbJKZ0SAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
