apiVersion: v1
kind: Secret
metadata:
    name: bot-db-readonly
    namespace: splattop-bot-agent-8s-dev
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:fYOe2SvkgfePDTs1xifZJIXG4dKdhpQo1KnnvccmdYD26575S9l62sYf/lBMd8Pte6eFg/iiLFDRLFdg+30w6bdlkWbNM7FFl2dDVRM0NjA/OIy69d2uUe38H98VhNeJ47OYhY1lPL+iMxETWNV9yiKNnBYVkIDobNGNvfoapUaOeyDIfevOYCMa/RjZEbIOxR8QrgRQBhP98ck1tm/VRj+R7kbjqkboHOGhzQ1G/Uk1wSkT7SWCk8WS,iv:7f3+FwuhGyo8F0dDvGqtvzQtMZVJh/LT5yUdrpqTIQA=,tag:JM9BpWSgtaC23dWN34cB7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTmZ4L2pWOUNwZy9JSGt2
            QzlYaW5KU1ExbVR3bkJLVFV6dXZkZVJVRG5ZClI5VTdEZU5jOVFicUdjUzl1MUtK
            dzcwK2ZsMUdJWTV4NU0reHNnK1p1SUkKLS0tIGRzY2ZaVUM4VzJnMVJ6UjNxdmcv
            MVlweXREU3FwNDNsNkpwU2ZPdFRZekEK1vrKnXOw5eAWxmJd1ASp6tU7yU2MeFo8
            Q3UGCmqNgEKrguKMIsGM4ShaqjMhV7BqaYgt/hHAzoMaXKVSYHFeyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T01:11:25Z"
    mac: ENC[AES256_GCM,data:5C11t2XbSbMRj29JLXfOqIy1LMbJWD60FBEZISWScJIe5bySh7sC3IT+U1+KdISWxFVo2YWVVCxqWRFYOf1elNRz5gp+cHzalmNUsDzapilYLpdVdT8crwOZzWucUgbb7DxQycgJMv0DoTZ2jqFIzIjxGavT3K6Luat3m6yVATk=,iv:xdUvEj0SdQMclSUDtFuV2F/oFE7o+RLXKFEDmzoTayE=,tag:9Rpn1MfvLCJGvW7BaUx8kQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
