apiVersion: v1
kind: Secret
metadata:
    name: bot-db-readonly
    namespace: splattop-bot-agent-8s-dev
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:w+SakTNMd3J201vMnCpxgRhD2WCJiHcUOiLeH5gkRsD8Q/1U2Zx41SP4tfTlg3nUFjyOUqRPky2j8Iud4lyteGwOy1p4E1tH8ebEhPSKr2M9qlNGIZJ6xU86ackPfusK1y2emkdSgse5VFhbjod4vawZbA82dFZ/U3HgDUbZL4jHziVkCpekRpMUh8zWmQdZPiymw6puV+ePa80YU2MDVo9j9r6qSVcGIwRKCQEDEKaO3XGu5g==,iv:VbzW/1AkP1crnW8hW9Tp2H/Sgu5H3nY3AODcpQfNUvE=,tag:n7/LxmpeR5NSeW4OKDHyVQ==,type:str]
    DB_SCHEMA: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQnZ0V1ZLckc0bVJLell5
            M2FGQnNwNFhmTzJ4ZXlPbWZpSFJab29acG5ZClZ2YTRsSWNGREk0d2oxdG9GM2hz
            M0lFQk5tM1hwSjIvOTI2c1ZhaFU4dmMKLS0tIG9FOWFmV0N5cVljRStNUWVtSWNs
            SWRGazRPaFlUaUtvUnpCNWpSTE43bUkKCVPlMBkoh1qDex1S+UmpuWebeo7Nsh/g
            +4f7wfAIvIEmvW27XmIzsM+JVyeepR2WA5R2AfS1XhQ88Nl6jAHxkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T05:09:04Z"
    mac: ENC[AES256_GCM,data:4aU5glbexH53YcbjQd2GelRZvNGfFtl5YNEaO8pqFtJWJTgdU2kUxp6dCe+5fvfo6tAN7E2ZME6S9tK2l3Ay0/+YCOcvLz+LCfa48vC+iUp8PRo9gBteyDKX6gnULrio33X7giOQnwAXjHRj6yYcwxVqHMmunlc0BpPwCXaAXgE=,iv:ADzgwiOTckfdq7iClnXajqDSxTLZHmh0yPqfXpA+abA=,tag:y4H/UtTXMYPq3R258rPLCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
