apiVersion: v1
kind: Secret
metadata:
    name: regcred
    namespace: splattop-bot-agent-8s-dev
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:Bo3tHSFiCf+SaiufgZpVuhUNyBXPI8ENKX2SKKnEPPIDXhQaEJ1qDXIXiFbZDlueRhitgoAvpL8/PtLqqCydcTtE9mLcsYVMnyRBnsF11jDpcvy/s2UPGqHPcAadX5xpybTvsWears0XXdd+jxMqqrJuQXQXxEkpa9sTGkfKohe/ak95m7OiEno4oIeuTpFilkVdNehzao5ebi8ta/Sw1rwSSTsxAn/2Mv+Ep4CaiolCJ7uwU3rtSonUg5lkJ+zmZhnAn43XexwuuGG0BO98ydy7o0RXnwQhRYiIL9r1Oa6Ll4tpzkjq7Lhl3BsxL3j+58h1BPmS2IKz+1Qs8nFEczohfsFlC8w5/fpKCdVSmdv+6b0wt5gfMTz79jG5pxLwtznn75WD3TA7vH7lilQnGxLbb3rwXFnajoPtXSuWZ8+9EPc+q4JtMI0GlptE16Hf0BoYa5IOMiMQivndX8HS5+/gRLIKsC0OgBP8TYt8iTrsOTxQ7rDtYS/5IJpiF7RzqHap4tnto61nELioP51x82R8BC3JtQh2RdazumqCy+LNBTwMRCWLFv1Z1OdbIglPpvQf8swG55EAW5N+60eMh3xX3ocKSfi8XAnRWrjSkg31DX6LYYT2WUrJgqbQG5OMRMi5b+IV/8YrbFyfcaV9YordqQfKqwkiOcs9428y+wlV/wtdoVfU3rAa0xQhrNzxNpw7OlpBwUZJ5FCT96k9R0tbHBIeCK/HZ8EnzC760a+AJCBFUex2voIGs1f7Cu0CSfDhsYbgn/CH5HhY,iv:v5kSrzBLqNNzdrbr83ZAzyy/oF3Yv0N34tBbF+l5YUg=,tag:3fC/L6sY0Rcmpes7l2XXbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UXZHSVo4NHhDa2VKZ05y
            cEdRV1NJc1ZYVTFlMkZyTjc2TFgyS2UyTEJBCk5EV2hwYit2VHcvd3JSNWxHL2di
            N0ZiU0dWemRkR0UrQjNyakhua2tkbXMKLS0tIHhGaFpyL0JLdFJEc1NISnRvQ1ZE
            TmdOMnBmRTROM3cvRGdybmpTbFRQRkkKqMofh9kCoqD/kR7WE30Vjnmz7l8IfaPb
            O0EFMQfdiE6eOn+5sYdPrixLXPFXr5Y7xaM9f+VeSq0tHzTjERg1xQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T08:46:25Z"
    mac: ENC[AES256_GCM,data:wP8OFVaHrW5F5VZEyAF4EaGGbmJj57Q5hsGKc3+PJ1FoNutWtjimAXCfXFbFqDT8UXSC19VjzjLedcrAAK045rDSjwhAL+U84prJ3oF75bR+jLtWzxAh3WT60ie2DhGvPK7UkvKeWyoSFUQgByO+hylOGV+IcB2XfhPMjYfXErI=,iv:qM5kTuX+vGViPEGyho2v1pvCZguaNlvcn/veyxaxnVs=,tag:8urzu2YFJcFnHAcrk/7c7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
