apiVersion: v1
kind: Secret
metadata:
    name: bot-token
    namespace: splattop-bot-agent-8s-dev
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:7YScyklIfgGbKH+2yjVuV/oZpzAD3eodcnvZuGeqXBOGIGu4eytPxnxwFi2hKbGU2+wdClI+V+OZH+f9wV/5GL1oYIURTgQM,iv:elqufIViYCqpErjPXqSqY0Nl4QXCKxcT/fqX2O5bZUk=,tag:pOU6Bjf771Zzeg4WOfwx2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VWNiNktjNnl6TVNtQklo
            a1RtS3lhVTQ0Y2Z0L29yZWI3MWkzQUFPU2hvCndPcDN4SDlRMlRLbmk2aWNxdG9G
            UnJpVVRUZXAxeUk5MXB0bkdxVHFXZzAKLS0tIFozYVBlM0JtSEdwQmRUSnkra3Zt
            akJjV29OT2p4bEg2eFV5d2pPMGpoemMKc5vVVfEYJJx5LmR8NVMn9GKHC4T+zOlb
            5fw7yMssVnCeWPDpyq016kXsupvOr4ZSUCMhPnTntC7PRFGXHiMUmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T10:06:50Z"
    mac: ENC[AES256_GCM,data:9ixD2GntoR4IvUkPHjutu53arzMdHdvCziPcnfKyvyUyj+9SHdgiKLkzwn/GA3oEfwAd1sWS4+7I7xTxvS5Opw1n3YMt/eUtX+4K3VLnwZWV0kMPXUuAUsakL5G4C8M+MtJW8GccAGjZmuOP+Q3Omtik48eV4YRoI0m86PetE5o=,iv:6q5gwjNRgr9D/6/iRRLmRcnah/1PjyghqX4aqs+0HYc=,tag:pIPzb6a6BjFDlsiz2/vSGQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
