apiVersion: v1
kind: Secret
metadata:
    name: bot-token
    namespace: splattop-bot-agent-8s-dev
stringData:
    BOT_TOKEN: ENC[AES256_GCM,data:FAOAEM0Xw0Bv//yZHluMxQhZIRHoOo8d8+WotKkr8AJuaC8jCjthKVYBP9qyVSb3bKofWfvhLHRzobGEfOy2sN6TReL7NZks,iv:fznkI5N2mA3CHMBUwFXy/d0KtJNom4hCV41VI3Pv31k=,tag:CbA1EBy+Dgmif8lBw9wdyA==,type:str]
    DISCORD_TOKEN: ENC[AES256_GCM,data:SpB7cd93Qr1POVIsRKJjXWsRNS8U/iTRSSj2zsqI0bNr9IbHwkFQ2aimTV0lVdpSSumyvpivqqlopBYTnTuwd5s6/flKSUOu,iv:BIYNJ7Sk20NjTyid+K98gXRbpUgwER390/FRSM8s2fY=,tag:zhK91lzw0AjE9h52oHTebg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVHZsNmdobVBUUEhjVjRo
            a050WCtjR0JENHJ6azdSaG8rMnl3d251MTBZCkUzWU0vV3o3aVlUdXM2VlYyT0RO
            V0txRWZpNlkwZ3BGcDVBek5nVUxRdFEKLS0tIDR6b25aZklXR3F3dGFsb3R1Sllz
            Vm5vTTA4RVl5RkZqV044YWdPMlc3MXMKc0iCkiqTywuEtXH42Ton0YOxTLLHUeS6
            PKlSTa3M2Sec6YYlnySB22FBCcq+Ncs6eix33yUrOKxqoklrUXTZzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T20:33:42Z"
    mac: ENC[AES256_GCM,data:MnqIrjWhtvrPubu326XuHfN5wbr89IFt+bXks3I1VAkD5frwSh2gtgoOO2wcKQuvSvE5SBpoLp5ixQUSOwB9FEvWgdp4zdhmTQnQUinvvdjtViX/BD6Z3nCbLp2TuaaGEOoXgrQ+1OdyVAtDRIlvxaLMzE4ZzoJbeOUjNX27AaA=,iv:gHaHweCegeio0rP5Vp4YeJhC18uKj0UOuwNdLAg7zAI=,tag:ThDgig+ykVbIjmXR7vdN5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
