global:
  imagePullSecrets:
    - regcred

replicaCount: 1

image:
  repository: registry.digitalocean.com/sendouq/citrus
  tag: 8dfec0f2d018c2a874adea6b0c115c8628abef6c # allow-latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

application:
  configMapName: django-config
  secretName: django-secrets
  emailSecretName: django-email-secrets
  command: >
    python manage.py migrate --noinput &&
    python manage.py collectstatic --noinput &&
    gunicorn Mycore.wsgi:application --bind 0.0.0.0:8000
  configData:
    DJANGO_DEBUG: "False"
    ALLOWED_HOSTS: "citrus-grace.com,www.citrus-grace.com,dev.citrus-grace.com"
    DEFAULT_FROM_EMAIL: "orders@citrus-grace.com"
    MEDIA_EMAIL: "media@citrus-grace.com"
    HELP_EMAIL: "help@citrus-grace.com"
    ORDERS_EMAIL: "orders@citrus-grace.com"
    BUSINESS_TIME_ZONE: "America/Chicago"


service:
  name: citrus-service
  type: ClusterIP
  port: 80
  targetPort: 8000

persistence:
  enabled: true
  name: django-media-pvc
  storageClassName: ""
  size: 10Gi
  accessModes:
    - ReadWriteOnce
  mountPath: /citrus/media

ingress:
  enabled: true
  name: citrus-ingress
  className: ""
  annotations:
    external-dns.alpha.kubernetes.io/controller: "manual"
    kubernetes.io/ingress.class: "legacy-nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - citrus-grace.com
    - www.citrus-grace.com
    - dev.citrus-grace.com
  tls:
    enabled: true
    secretName: citrus-grace-tls

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi
