apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: splattop-bots-netpol
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/cesaregarza/GarzAICluster
        revision: main
        files:
          - path: apps/bots/*.yaml
        
  template:
    metadata:
      name: 'splattop-bot-{{botName}}-netpol'
    spec:
      project: splattop-bots
      source:
        repoURL: https://github.com/cesaregarza/GarzAICluster
        targetRevision: main
        path: helm/bot-netpol
        helm:
          values: |
            permissions:
              postgres: {{permissions.postgres}}
              prometheus: {{permissions.prometheus}}
              dbReadOnlyVPC: {{permissions.dbReadOnlyVPC}}
      destination:
        namespace: 'splattop-bot-{{botName}}'
        server: https://kubernetes.default.svc
      syncPolicy:
        automated: { prune: true, selfHeal: true }
        syncOptions:
          - CreateNamespace=true
