apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:+UYlVOYKktykElVoM9Pnrb9spq/hwejFHtfsV8sfsqvwP5hTjWWAUvYtAoymjcFfCfp9CC0BppNZZW0T9zMpGVQfi+sWVjLhEes0GXVVQGlxlE3aR4r2aLf3T1/ffSSqs7BfVG+iQocg4XH9A9aisIOsXPwcwbKtNoLelI1I5eMjl0ZYZ/ojDtkTqCQFCVuoYFMoaGo7Ze3y9sj5LneZQZbNhuHuPL0+sjTvRyDgVk6kHP5VGR2+FJs1J/kXCX+3BvAS919aKY+HFg2ULJ06o/8a9TiSZ75D/D4kgBH9BXX9sXVaeEbipeHrunrYFeno2UtzB2LSiDiO1tPykPVhFW/LulBPC5yS4OVrVvz2NDFc1MRCgj8dPIaPinogbFu1tEEM1y5Bi2tbufniffoCmhAkeST1WD860Y9NpfYDVZA2+biH5zLIayicHYISZvXPqi878JYv1ZYCfuw+G2rxcQVN8E2rHC9WI96XgDjjGkuX2xZesXzmFWq+GxnQwCjT1FDKrGi2bENA7XSgIc6jwRdFvs6oqs07yxo8uklEXrteHLOhx3lShr7Se1WiNMuSv4flNA8X3WdN2RgAwqrk7jmmm4xB1ocXXzB13vscYxb3MzGCpsmwz29f/S8z1KjpYKm9I836xd5AlF1whEcDl7WZR7kyoarkjqg7Dc/4dUxSM5TG/WIy+DuE5D9oAu5c8Zsmgpe4ST1/u7QuckSsmi+CSsukVeHz8J0dhxxBsQ70vAc/h7ihC3yHiXrygfZ2+qwhb6Zdj8xAkdjx,iv:nBo9AKYw3z7usvsjfaQqMW2HtKZ0N3QMQfcoNX4IkIE=,tag:MsZ3BflzFaCztwf/uMg6dQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: regcred
    namespace: garz-ai
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MlFueWo5Q2lmeVZQN2dM
            OG1RZWxGaEVSYXUwVHMza2xoNHlCbWNWeDBRCkUrZ1VLcXU2U01GeVViOWdkOEQz
            MVVQQnNWbyswMnZrMDVFc0l0R04wa0UKLS0tIC8rOUJxSFFlRFdtcHV6aSs3SlFL
            SzVHdkJhQ3pnSW9SdC9FeVIzVTJmcXcK2xBktXygfisOlE5K8jimABPmCQ7sAR/G
            LCPblfcbQn/2AYd+VF+cSHxmIy8wKtPsV77F/+VFxHbC/sdDZ5c9tQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T03:24:59Z"
    mac: ENC[AES256_GCM,data:A6pTqRyiAv7eZzWQjP41MYmZhGw9TE+d2qTvu6sAzeb9USoOXpQtpL/8k64GsKA2t4ZDzbd4M4k8KHBwYzlw01ID5kQE3TPg7HesGhbN5vmaReuwNIPyq6C8P3wbh6wTMf9gWptd+WFGbWYkBYEJYuBObrTWzfORGZGuxEW+t7w=,iv:p1z16s9M8wVgJL5lk3DKicohKwz8ZMAes+9kQ3GX0f8=,tag:nkuo1eoi6KgF3G40hgRO8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
