apiVersion: v1
kind: Secret
metadata:
    name: bot-db-readonly
    namespace: splattop-bot-my-cool-bot
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:BKlXm4lIT1v+sVEQQOACDfD/5rjMEo98GgdbPDemOiU8lUEwoiXv/YByTZPycNstKjDsJrBOFjzUDic9Xy3J/Kyj75cXnL5yqIWxaO5NqIhNvUtlV9vvVwkzzAnDG6AmqpZa+uEh8rhwKftp2/I3h7zTPIQAjo+owyqGqpU0fNgW0ByWUSuwrd+d40oDVPiRddbWFgWg1ULNd9ja,iv:BpfAYyP9FuN1F2I0288Qfo2To6BTSCvm786klLSU8qg=,tag:aDyWrNm9wwLUoxZyX3uWdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NVgwZitjRXdxK3JLQnI3
            R0RKMnAvdGZaVUVVY0VYZnhVTS9GOGs3bEVNCjJLc1lUQ2NSSm5RdVhnbjRsNEt5
            eU9pK0twYlcxYzZyRTRzUE55MGZ0cncKLS0tIGJlbEJTMlp0aGhQKzc0TDBlZ3ly
            R3RLSjFxWmRKbHcvak5sZlZINjJNS3MKSHntAG0TFv8s2Oq5bAXiG4CrBRBA05+C
            ee1vKArDgKonK/Qdl+RWtPUzGaYlKO8SnA6LmFw4CBbxsg5Z6FL+ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T05:12:00Z"
    mac: ENC[AES256_GCM,data:4b8z57EuF5MSJZxPprYwMPCkb5/6mXncSx+BYxC9V6Nx//iw6NggRKopzI+JW5EgdSRcGSUEQ4d308sre/IO9SThkZUCGz1ycoZoS9u787riOuUt8O+FumpMV68huQcXSM37JyeRNedrP2sfn1TMt4IlwLXlSbDssW5VnI8IulE=,iv:fkpDthokNU0Oy12AxHx4z9bzdN+m60ZMV245l1J2nmI=,tag:KTE9UmMWhQOn2GBtH7AnjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
