apiVersion: v1
kind: Secret
metadata:
    name: citrus-dev-broker-client-ca
    namespace: agent-workloads
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:4feWcg7lK8Z/aITBSPxS6nDrJNKrv+pWHHDsgS8yzuvG0dhmB01kUzk0Tl9+TnhpIRNVkRhVzz6uSDOIEnb6dtJEHLYDcgLJqOEU880NR6iRGbkTIT0Mx/aahQWHqxDEEmdYoedwbgiEdjcNP+ccDn6Q8BOV22Gkss9YZ/LinvwZsQQUi2aAgvYNI+nORqoB3mBtEK2HThm+d/zalXyuQffmjft7DQTXCFf8p9vg4oeYZs0Abv1sA/6UUBSbDvbszwUJq5hSXYZ1usg0e9SCtMNfpfuSUVtAqpmlE+0n+ZszTGehDbZN26S81X8fFZG4qg5lZKT4NB8X0fPH6imqpdZUOwLTd02XsB+AlQg8LCWsNFOblQn55Zwr3sRH5nbE/X3/ZL31WQjWmTDTxW1a8UQFklWgiNvm6ZeONpl5t+D+md/CrcQ22bbNnjEg16MNy//C3HsWELbzzsRqKewGTD7KzWM5OfKKZv3OYTTUc6batBzCy/qTSB9hIcXBVkKHf4auK8i7FVV17WONi5rmDeiByBFWmmiaC0qwUrgR2jXVV8jhdV+zpl1GUGPUbfc1+BC5rr37yRnd2K6c/JGgDpPQ+toZ8p+OV/yXBwkQ8R6y5D4vygO+yfFIGq91bz+Z3W3hiH/ojMgEahhhKSaYEBQQt0LuYFk8aDdOgEG3klwsBHTd9LacDOE/oPwlJkGdInsLBAThGOuA4/rwN1Bw7k59RCJqLSC797Vrd1rJu1Fp1uoOs5ryMc56XMXa/juwZ7rZsBmxNxBL7IhArvBOxM44wc3F+v88PIxE4SU8zcW/xBFaqqCc89aAHJ2Tnwhu4nnRH44h/wxOwQpJHV219pNH6QdHGMPQm1oIC5T2pNSLhd3e5ddzTw3+Yk0=,iv:NEm8qXdjUFo/NnBBI3z4W7bvfQKKpugTmRNIhSM2zd0=,tag:a/woRXi9XJzyhgyK6Rutqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRlV3K3YxK2kyNlBVK1pN
            SnFnWHlieXVXR3ZsMjgrMGp4aG9NUFpnK0djClNnVjdjemF5MmJsdFpjaE9UMEdN
            R3B3WTdFdCtXWUpsdzZlZGd1ZXJwUDQKLS0tIExoTkFIa0E2QWtJOGJPaHhPV3hW
            bitTUEszTVJ5TTJ1bkV6OXBNeEkycHMKVoGDKOtHFlU04bgk9Q7uDOIq72+M7zpK
            +IBLql6GEKkhA/KVrPlUE05mLQP1TcF4Pq6BhMVf8Py401vmYVnRLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-28T07:51:09Z"
    mac: ENC[AES256_GCM,data:t5wGuLEGGCC3RN0UiDjuuK7gmi4nfXu1DhIA/2TJFpK1kUWQnyP0Yj7KxhF4MEbx3WLRCPF1NWo19ldro+ge9t1g4tMnHs9pqBeTrvJoXbp5igKNtu1F1MnQz1GtdPLD73MYfqwBxCC3yTIlx0c6bw6x915f3T/s1vnPW/BGqMw=,iv:FYAorCGdidNWurB8W0xIAvGxjSF+1/qOBVGWvFLlG8U=,tag:KVWa7DcENqEfe6AmH2pqyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
