apiVersion: v1
kind: Secret
metadata:
    name: citrus-dev-purchasing-token
    namespace: agent-workloads
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:sbLmvCTtz06MN/CF5Mqp3V4m3YAVLQEwoMzDl9Bbmu7LyeEmfgOXSY4ktraqSRDtDi4e0pW56to6RwlBa+UZ8sowWpDe43NQJzUBSo3iFnIDioRjYFvYw9bjoIHgm/M=,iv:F666/C58xbJKETLAtiFjbJgAYX4723b4ShHipGq5/XQ=,tag:dQgThvaWGoEBHwF1IOZXCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NkZLa3ErSXBzdGplNUlk
            ODI3YkNKRkl2NXdVcmtmeWJBNnRPTFNWR1U4CkhRTEh6MGV6YWxWN05Lc1pEd0Zt
            Nk14ZHZEQ1pPamVVTUJrOGRmbjBjWkEKLS0tIGYxdzJhang0ZCtLUFhUYkREUmNE
            emsySzFnYTBDSkZnTjUyeHRGYml3SjAKSkRsOv2EzdARyXox1/AGzgYmI7y1HsfO
            Qhrt+irEK+UFi5DZ70t21ggfoprF9CiMjq1JSVpovqPCxG1zr5cM+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-28T07:52:52Z"
    mac: ENC[AES256_GCM,data:+nQKXQK+OPvQSeqxC4stnlNPN6kCc7BfjLCenaZcDra/DJtIBxdqYQGsTjre8UUcdehNpS5derVuqYl1oBhMZ9inTkHZLnq35Ku1LOszLf4CdUXJ3h9HFBkve5fkqIDiWNWyXfetoNYFO0S/y0/rQN9JkaOp3d9Q++wlym15JYY=,iv:rVEb6MxxTnTA5sH67xfzt1Zyyfyjkgoo7PRG5fbXgbc=,tag:O88/PS6dtP281ENQaWSE7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
