apiVersion: v1
kind: Secret
metadata:
    name: citrus-dev-broker-server-tls
    namespace: agent-workloads
type: kubernetes.io/tls
stringData:
    tls.crt: ENC[AES256_GCM,data:pY8jDq+6V/7DAW9AtMWh+4aP0yimewcmo7Fb+kSaiTC1QRSZ630/4eR02zoWgzemmrh0AW5TupkPxjODG0voq7AgUcRnFQ0jgVoDtgiRc0neE2uL0a++kHwuy7ABYUaYyKDbBoGzVh6CgTKnonlqI1r2FPJ8yujt4upBrIo8taRcLT38ah5KfV9kVBmjmmO+Ra1+uoP0fFn+4udw1LnOeRvbW0qWvLPQU1Ku8RHaUuggkRDNZmoPaoVBEIdW3JL/inm8d5kjioMK0eSCygHR5aBdgTzSKkhDTPleEY9d7FRLyyA4pNcPz0o+KY0bsZCshYUjmk55bXhWYyGziAIUM6vBdvPsQp6RqUA6HJsOEIR6k/WjT9bIpJsPlfz4SA6hO8VhzJg7sdSSvmxitJb2ussLx8HFjOf0b1Ha1tvGLhZ/UkJGVOwJDrMRoyppvdkO/1QHmsUqSqB24Ohsl6lZT6+FaIq/OsYJUqhKPJvrNA+mqVi++ZEzv3zNoRY0KtcO3pvwfUJZOFuk8Xponi8NmowwzX+l05bfWsJSA++FbctITC6YLZ5Ug8+fYExttdIwTvp/z5SmpI7fy0BA/32tIg3q6QZ5yELhdxj4S58uKHXUjdmLR+IAsNX4KXGapr/PcyAMG9suiow/wlJ/kFTbbqCr+G7cEqD17DRjKkvca5fEeQDkiyKr4K8tyOYN0DOXISzQc7HMyvVVe4RloldtybFCCFl2g9a+/rBfFXMTm1f7y34o3HVBfvbNw2u5yeGGk38ltOnf4r6jpKUBweRLFOwLM+sQkGR53mXRdBAIAzGvwyQR90ATJDv7S47rIWIGxCFW7K0S1613i36KQ/jYtDvn1wgET/4gbjc3DiFGbLHydgbZeJTohEoobTk7Je9+k2Av7geDsGlyENt4h8JGH/RUErAQU5lJVQJ1ZlXsVgHySd9+/zLigmUq5ci11tNzhGGvxmzMeMiYQH/e3+qzY/Z7E5aM4YyaVDTCV1/8f+d2XtEbQu8D8l/8A4VeDT1OEQaiTaEDasOIiCCNCscDym2bAxnQxS0CYkY7bSvFouvoxw==,iv:o/i21GQPhONv8bOFEq5QQMd5q7WBg/1vYYRm1OuyWEk=,tag:8HthnowRAri749o77hLVCQ==,type:str]
    tls.key: ENC[AES256_GCM,data:N5TuapCND641xq78bhqoxuA66NUq8QeaPuaYUnivcfE2CW/mJ+20Q5541Y5pFgiE/Bmmj6Nse5Tu2ZSF5ZYITLf0++pJr54jIrtlzTeUdVqYbugmsnmsJgUTweILqYWPOzVBrQRLbxDGvivNCj5mS73uXQ4Ykd0yN1RzU9E2EQQlR8YU3KfmJxz6ptVBJLwk0mwTtIwD6SlCGNg49nu71+cE1yGmrpic+xD5wpdGhUbt35RRX8uGQnh7rP5sonxqSn/UT0b8aDoz5HBGSwcjay990v8/A5x0mDDNtEu4tqRuOpSBrMMIqs6ISBEl5mz2fw==,iv:LjApI6Tg0vavOVHzDOnhNmIwQSJt1roPmuzbzANsj58=,tag:OkYAdP6M6SqhcGOHywnvtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvd2V1K3RzMmg4QWoxYzZM
            dDJwOXFXejJIelErVHlYT1FHNjFrNkxMNTE4Ck1Zc0ZLRVNJeGwxN01DUG1iZThj
            enkxQzBmZG9PUnl4ZWU1MkNHYlJhelUKLS0tIHM2S3F0dWtjYktxRGxMaHA4ZmZM
            eDBhZzBCRU9JSlV3dVBJejErelphQ2MKLp66UpwH34NOCIMdAirqKg6UhqV4RtzD
            iID7yARlCioYvyDiJBLpq24/J4W/WU98yWPkduKtgJwBqVXb6Pzvag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-28T07:51:09Z"
    mac: ENC[AES256_GCM,data:Mc9oCfSySEfTSMGpHdoCYpsDi/7lKn7CKnYL5dF1BpofCGtzKPySKJAgrdkCB2elnkba5QzKeD8G/h7+nz3Bj4PC+efgyCHcqssAZ7OT7MQHeQqVD50CPThPe5NDd+dWdP3kV3HHZfxquOCLl89gr84CGDx3E1obobLyMzwRaeM=,iv:gqv+kBWky4AFPOvmhLHoNaXzt4kRqCNzqmsKMCIwPDA=,tag:ZqfS4YDfJNHscqYDP3knNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
