apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: agent-workloads-secrets
files:
  - citrus-dev-broker-server-tls.enc.yaml
  - citrus-dev-broker-client-ca.enc.yaml
  - citrus-dev-purchasing-token.enc.yaml
  - runtime-secret.enc.yaml
  - workload-identity-tokens.enc.yaml
  - regcred.enc.yaml
