apiVersion: v1
kind: Secret
metadata:
    name: regcred
    namespace: agent-workloads
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:HlTmewzIbJvjnaUuu8q2yoXh5wcNOmucTzmp9LKwFoZa8O57h0VLVhyOaZVDGVnpHnWOTxC9NGOqiNJiEj3TG1GqhkWw+BymYt2Wic9n/GHpJVwdLxyjBbX/mMHFjZ/hsX131zDtGFLCGWbqOtoDqI24dBiLRBHzAxRd6TLO9iLGk9ypl+JeilgUPzUw9YT5pquFoIRRXHqAis7aIRB/yNL5zCdQ+2QGUj35Cr2oWQ/VsTeDO5+G1elkmzB9ftN0oy8onB9COStS0MVF25HdCPbjwMzb+0bNzSTnwecHKB5lqYwzAb5NrTX4HAYRgOsR2BIABpU2/n6+ncTX1zD//jbg+l1HjxcSYfUUStkmZArIzd+1fPsH+M1qsGMabH0lf2V2fkzLq0MIacPE2rFBokSkQBK+q5pHAf+E1ebm4+67minQ5n4nsMXcAfuOiM0GY/ElTmynPkAppv1D6df7VPJQ7YfoFCves4QCFKc0nce/sad98+KQgUc//X6L5//cir1Fd5UOCWAJuVYes/6oHZiOem+np2CbjSiutcFD1Qm5TubjJ0YJMQtvGmLNMDiEoh/verUyZthM1+Mp1yOI4kzJOPL6duaUQX66Ls22TD2DQlmlv9C33y54LOdNunriRztrX3nbM5VJyr90gF2d/rs8+m69x1keQHTTFEnzZ0ZjEA9DDxLSt2GCfawO01142XlM1h26lcmvsvp8S0MD0qHNwA6B9WNT,iv:IdrnIY2nvk0iWd9hwC5TMBozqnTnvyx6rID6vaW03jo=,tag:nvE4A5zG+8Ih4UXExvLWTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUm15SVdpQzRvbDdhb25V
            K3pYcmNFY0pLZjlsRzJmd2NGUGJaT2o3anlrCndpenB0Vlk3clRwN2t6K293a0Rz
            N3ZsMlg4bUVuTStCMmhDT2VkazBsWUEKLS0tIFpvdjZXYVYxYkpmUmtoY295b2pO
            bXNZVXdLaTdUcTlkOHJ4anRhb3YxQnMK/WBjI8/WTcFHg+9WQ/XS7spdX2b7Lvzj
            snd3kcKJ1c023vlLcZJN9Zwr64qMm1EemBbecu/LDZQ2YbGesp9QrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T02:59:21Z"
    mac: ENC[AES256_GCM,data:vm6NPN1G2YwsX2vUqzeQ9830s2UazM/VBphloF6UpZ5FmhGy9gSC6+c9mewbs1m/HLUpUiar1OzN6dElfKOilx7yRS3yG4TKSjp9Z9NFxVzij5k4HCVJrjPono0JYv0HLabcyquRj8u+H8mv4km9Ec3Pjo1X5Q/2iTXhxFlOvv0=,iv:AAm0CuesTxCjv8c3pzjGPvhWjQ2GKOJS8B8Pqctw4j8=,tag:+sl+ZLqwdLyh052v9cy+tw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
