apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:+Uj8oe+S7+QDQlW7aNELU4h5446DrSBU4DPFZPPLO7bEe8e1xiyONrpOlPjIjS4r1brka1cwvwp7yz+Xun7tA/SBgZ0y4F4Turm+khARlibf0gbpiTBS73YZOPP3xcmL4f0/4c63V2f22iXrEGx0rK1TpaRkrOQThVbp3rT245r4SXXG3XAJUbtuc3Ua5SYP7a+mEYmvr+RFW9QEf4YygYB24URyZZAHZRMg/gx2eQ//QPnngAn5sYg5lOy0sqqauT56sNPg5Hbnb/AqqA4xhUuDRg/LI990cpjGjlu7giFac1Ks8eqoh7plCWu6thLm9Y7NYtJEc7vUL+tGdl3P3hMuKzopN76fyNu2UhkWTk1Nw/7rYwbkmz49AFtCCwzx9odePQvV4+NQDDqTLPPLsQwGW1yGsAZe/AdZyONHy7bXuE4elyDQ8vFww/RjzJY9ow1xg3y/EyniFuPpAWW2w0+flwRBQtUDIPBNOWNE7YZTR+vRA/Ar99paf/ISYQGeGd/e21HJ34oOPbhbt07txcDSCoznwpfLD9K3Noa0NiJ2GH8ZzoZ3kwjc9FZvzSugZNBH4nI6h9aYy9yqfUOyXc2r0XD4Zk20fzTc4LYQJ99SwQtvP88T8EABBwAqMYkAwKpZkxdQbsgKeCkw/kSU2eXBTAlEctyVqcFe1RvkwP4wjx1iE4GJrKtve0nWCaEp4QZ5HVNbh2mDPWGvnYcmhABy346qvJs9LUD0SIKVNH5rqfVMdx0Y9MCFrSNCtM23zhU6VNua3uGsxU3P,iv:x3x6IdUSFmvUrzk7snMZL74TasYX94L6jzHTY3CIuUk=,tag:uxxmZ5zJIpj/3VtUCZmuow==,type:str]
kind: Secret
metadata:
    name: regcred
    namespace: agent-workloads
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLd243L3BlWFNmRGljWlUw
            aEh6MmEyUzhkWlpOckc0TnpaM0EyQ0hodFJzCjZnalhnN2wwSUl3SWlrdXo5VnRL
            YnpUekRmcTQrM3Jlczd3dWRIR3hiNG8KLS0tIFdjdld0OVhiNGNKRSsrUS9iZmpj
            Wnpyb21GS1VuMzRmdUl4OTV2YlVHV2cKcx5u4+siOOO5hatrvbWzj9HnFrZdIJX1
            B4W9yVV8dnVazMMnZ1tgH9TDrBIvvp0DjLwUQWPxh8OCNpRk9ox7Og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T03:38:03Z"
    mac: ENC[AES256_GCM,data:toQR+qN6OsWJbUi8Eq77yrwAC93cosInif9x6M5HObDrugXNRs7dz2usuek6QoDye+XtrXDiLF82bX0XjPTFik8gdp8qFyWGcWR69r47rrSCIYV1p+/JWckaNgqA3+YpwSbZhUIe8hSt9LCmShjdFyxznkEYaEtXWAI6EQtlqsQ=,iv:YlBEWusRX9Y+QIQlI5UrwCnDrKNMqWFgWXG9xbPAHp0=,tag:rQWVxXBbcgjcxSaRtIHXBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
