apiVersion: v1
kind: Secret
metadata:
    name: agent-workloads-secrets
    namespace: agent-workloads
stringData:
    MANDATE_WORKER_TOKEN: ENC[AES256_GCM,data:LXDkgUrqDLCCAHjHVz2CsvTh1DjS+InvqDxgsIEBe5qwfA+8+d/X/45ztkbjJI3wPqEt3Vf+Mw5MY7EToHBA3Q==,iv:0Xqc8D/+qvRbgJeAaaqeianOT/zFVW0Mb5+2nzRI/t4=,tag:cVgiwSJjR6qLMmFwDKSusw==,type:str]
    AGENT_WORKLOADS_DATABASE_URL: ENC[AES256_GCM,data:3FM88lXXDZIYeytV95YZp866ckH8fXDLQDli+C8OwOod1dEwLuXfhOkb0HKUZytWWqOC8oLWrl5cZpuibe2EMH843nNMa+mtNQtv1AdbpUuJ4AhNJhHzTrl5mBTq372I1s1jF2Rzw2hfLKXigyPfvdGEVZSt5NgSFYVVf7O5ED9/F/70Tz1T+W9dtErloAsFd1/hQorkJC+fXQ4Db9hMDh6QaDDq8yqF0UxskmyhPup554Zi,iv:kRBB22p+HxYxYBjnnLDeDY0IukB8k2UC8AUHj1GhIUk=,tag:K9Eqk1gp3+4/DuU1qdxAPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cDJYYmNMZjZua3ZINUlq
            NTlOTVhiNU1DSkhFRDJoTWhRSnZJQnYxT0d3CkJxVTFZZmF5bUN6WWtERzU1M2tl
            RjU3dlJocXVuQktTU0R5MmJXNnZpcFkKLS0tIFliNGlHbk8wUkp3WW1sdVl6TklG
            MHpkL3dWbzhjOW1xSUI2NjlWMFM1MEEKOOh0v4i0gtoK35tRaNrBlZqPzYCPfS2c
            aDiXACPmicMJMQZkELRmJJ3/nNS1DFOMNROMJ29XQ/7yoS67V3JMgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T02:59:21Z"
    mac: ENC[AES256_GCM,data:Ty/U4syWDVP2zMMN+r6RmX+++zz+BRNzQEUj8kRmWUtm9QrKyv+J2/DVAqXVrJegswPZDvV64xdXHbgq2HGtm8AcLGDWURxObYZWqkbXwrLSoM6s2I6qkxjcDH+gQISLBnWPanZEsLVGcOJFYdNOVm/Rh+C1MF5DSKSHrUHUov4=,iv:CWkP/XNaF2eiCvYa7EqTEtnaqiIPFWZ74T42zz1RKjM=,tag:PblZF/BpHJBwiLjzRl1N8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
