apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "health-buddy-site.fullname" . }}
  labels:
    {{- include "health-buddy-site.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.site.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  rules:
    - host: {{ .Values.site.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "health-buddy-site.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
