apiVersion: v1
kind: Service
metadata:
  name: gaic-traefik-ingress
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: gaic-traefik-ingress
    app.kubernetes.io/instance: gaic-traefik-ingress
    app.kubernetes.io/part-of: gaic-ingress-migration
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: web
      appProtocol: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: websecure
      appProtocol: https
  selector:
    app.kubernetes.io/name: gaic-traefik-ingress
    app.kubernetes.io/instance: gaic-traefik-ingress
