apiVersion: v1
kind: ServiceAccount
metadata:
  name: gaic-traefik-ingress
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: gaic-traefik-ingress
    app.kubernetes.io/instance: gaic-traefik-ingress
    app.kubernetes.io/part-of: gaic-ingress-migration
automountServiceAccountToken: true
