global:
  environment: production
  appImageTag: v1.0.1

blog:
  replicas: 1
  image:
    tag: v1.0.3
    pullPolicy: IfNotPresent
  health:
    hostHeader: blog.splat.top
  env:
    DEBUG: "false"
    ALLOWED_HOSTS: "blog.splat.top"
    CSRF_TRUSTED_ORIGINS: "https://blog.splat.top"
    SERVE_MEDIA: "true"
    USE_SPACES: "true"
    SPACES_REGION: "nyc3"
    SPACES_ENDPOINT_URL: "https://nyc3.digitaloceanspaces.com"
    SPACES_CDN_DOMAIN: "splat-top.nyc3.cdn.digitaloceanspaces.com"
  persistence:
    enabled: true
  migrations:
    enabled: true

ingress:
  enabled: true
  hosts:
  - host: blog.splat.top
    paths:
    - path: /
      pathType: Prefix
      servicePort: 8000
  tls:
    enabled: true
    secretName: blog-tls-secret
    certificate:
      enabled: true
      dnsNames:
      - blog.splat.top
