apiVersion: v1
kind: Secret
metadata:
    name: skyquiet-server-secrets
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:pGTBCM3B1k7qYA7fwi4v1Audj8DHvjMg9ddJMAJKgwhnL6zqCxWUcUp0I3vJnO+Swu6C1+660HVbAqYbn46Yiddc5GNpaCI7KhNAURanYFfXSYyNERj74sA6NzGOW1yNSw0sx2djG/BRXKgV8E4MZbbvWV0Woate5FEh9fS4V7BQTycnnuPnzsuwqe1K+NDb3GP/CcDpWQt2ExEDW4pDYWQawYAblQZnHHl9Bu4=,iv:Af6SABQ8prvTHAr3H/sqhyVs67iGg1BN78CcxY/NEd8=,tag:qmvZ0YgTj8WZEXBhWXT3Ew==,type:str]
    DEVICE_SECRET_PEPPER: ENC[AES256_GCM,data:5dZRue2IQWP2b/iZ1i0jypE6/rvnRqndwz7xYOYD/Qmi65E6s4UBf8Q1Kd/qLDDIMhcjIF3JaoJiAlo6XJIlPQ==,iv:M/PCSxPNXzUn6BAjY/w7RZOYHkncn5mPkBe/c4eDcXY=,tag:pwBmYlOKRS4bmXaCCRJ9Cg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZks1Yko1KzVkTlhJTGlt
            YzJqUnFqRE8rVWltVVpQOS9KcW0xZGJVTjNNClBUWXhQYXl6L1k2eEZ2cG12Sms5
            dlg0Z0JPMGRqR0JzWk5ld1llZ2ZIblUKLS0tIHRkeDBvNnJsTGlxSE1hajdrL3lm
            VlhsMTBiSkVrU2srMUhMcTJnN2JCWUEKbhivyfUn4f29ry7fUkH1oyezldC0dP5L
            e7/+VBSlpyNzbLii1ALQxpzd5YaiESvp4s+qAghHo7W0T97At4ExOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T18:24:03Z"
    mac: ENC[AES256_GCM,data:6bA68gHFjueLluleqRptEiM35gvvpgPMwr/REFBNHiLlneveKKZsWweGEZVLqny44k5KXV6Rtjk9EFKHPIy7iC68wsx8Xq7rBhtdigeOGQz4lQX3rLFtWvmY+qx7BF/kDWBnDqxT7LXBpZah97rsZvnXI1FjXa34jH5YjpVHQr0=,iv:seQbOYTkrPEs0BYR0dZ+Dlvb37fZUsFKGOeS2C0XcdE=,tag:mdqmSWt3hNgHrDCVFGvDjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
