apiVersion: v1
data:
    STRIPE_PUBLISHABLE_KEY: ENC[AES256_GCM,data:GcUOPn3tH7eNfp1ItsvA5LtSVc4Tt2OZVvJi6f8fVXpHC7n+iKDonsGP5mTtscw29knc5uuyYNs+usTkMPEc5rH7K+pG2BTKzHMCMc/kih92cO6gjKnBVDIfEnH7PzNrEcs6arOSYjGKn2azwdJ+UUij7jvI9acsgaWAeya8JRzJvi8C9Oy5+5bRgbgJtdML,iv:S5WySbsHA2UelITBzxuo/Y4MSNz6Wok2PpV9PvyLVz8=,tag:RPjbUDDjmR9U/mVhiZdi8g==,type:str]
    STRIPE_SECRET_KEY: ENC[AES256_GCM,data:JHbDj7BebDFHsi64la0SiJ8zn04IEfK0kL52K2KY9JgHUQLQKCP5Luiv1SGu9a/OuMS6VpmKNoDgR8I7XrdJb5t1bo6GZZWEpwULMkPLKlLwKMPMsdo5/NXHSs8Kc2PhStkVRkwVu4cD/N+aUviz85JRg0yZ9HuUELgQpLl4TxOy+2Vx1NvIkqXNC0wcxtxu,iv:hJGv/w/roziSj4M+kydfUUrRmwlPYbaSqiO78sUQ0dI=,tag:tRBrE8N5HQAUEeb9qarJig==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: citrus-dev-payment-credentials
    namespace: citrus-dev
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTSt1WkJlenVJWU9QSVRo
            LzNnMGFaN3gyRC92WDVxVFVyZVhXTG5TQzBNClUrMVRwUERsc3ZGUEY2VU9FV21R
            UlJZZGR6SjViY2xRN2gwYStXSjNCMmcKLS0tIDVBNnZTd3hZZ1QvM0VBY0VRR3BC
            Sm5jL0hqWjI0N1hjTVRWUzVVclNyT00K7nE5TBAPfP54WAwUbLY3BZ4gqrKruEgs
            ++8dQ7/A50gT+GqpytRkbE+7sv11U77+XGo4g9sgGkUInXgvGV9qYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-12T06:33:29Z"
    mac: ENC[AES256_GCM,data:dCbE3q74OxX5b6TXJ0WyhBLqbIMbj/8AfxnVh72ej7l6U97A6Gb0/hwowJXTz1ysOKr5Wxxl+sCKJfCO2hTDZipiPCWjHlkgGIDLMB7UOPbhvdBl7Abg3COYES9vFx6Oyw7Zm7FQnwDI0AjCpauc4U6Z8MhWqFWKg3kKrl28CVM=,iv:IDf1YyvpwBzEmi2Ct02F3VwkckmSAl3iUQkypqMcLfw=,tag:3oM6vf17mgsusseZTjqMhw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
