apiVersion: v1
kind: Secret
metadata:
    name: citrus-dev-sweep-runtime
    namespace: citrus-dev
type: Opaque
data:
    DJANGO_SECRET_KEY: ENC[AES256_GCM,data:cgYdsHFB2N8UQEEQbzm+6I4t7sxyNmdhrukEyIbqPKWhi/JmOul9JafWvIB8Vfcg7yPoX3QTPSf2FNrct6jjUJhxdF9oxT/w8alZj/WeBLYC61kylkrVhQQqfMJLzT9tIdDFW6m3ljYq1TV1dJWhag==,iv:aFgUm6XQSE2enOV5pMezLg+HQIgMnAHJXUxHSHXfpNg=,tag:pnoUs9ltFP+xLUWxh6OCqQ==,type:str]
    DB_NAME: ENC[AES256_GCM,data:MqmwBHCCPXMrLWuo9DT3rg==,iv:FJw2LBz7nJljXxOEYQU6rdKbw+KhTIkaNn+xmBpLEAY=,tag:KrD4M+AQRRAQK6AXm3uU5g==,type:str]
    DB_USER: ENC[AES256_GCM,data:t+EpeDcCnWI+6Z2catrkKTDiVdU=,iv:Tue30UTgmyt4fXxAn1XRTKRtJjALOaeI44E1ZuF5Tbg=,tag:jJ/0esNYdpy4P+GAwbYzFw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:SipMAM9id3w714Hhnmi9AsvyfKQyqK5lqJqFk+8LrPo=,iv:6fGFX1ZmR+CsgOrgq3Rn2iSV/SWRSNI/OBamxBTS/Rw=,tag:J6mrl9H8D/yuP7aI+VDVyg==,type:str]
    DB_HOST: ENC[AES256_GCM,data:Dfju5mtO5Kl4YfyUYyF5AxlXy0FKYzHTIUnNxFGnPwV4XLRN+nFoEYDX3T4hWNaCho0hUrnQdznSb+1bHWqKm1OnRq7k+aHVIqXGVeWHshI/eOkta6RnVAM+5sWybQhXeqrqGqDBZD4=,iv:VsV7Z7iG2Ks6XAJSzG6WLM3Uh41i0L4MaMcSXa3e5BQ=,tag:K2thUbxSoTQrT2UmO2k3nA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:iqsk9jMRjhQ=,iv:U3fBSv1l62S9WIYTK9xlOL7DojfQBRJXAOEmpGTgAhY=,tag:XnepNcDB50B9xDWncD1S0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRFFQUTlpK1VTRHRhV3JG
            emF1YWtkWnZHeW5vUlFqbjU0d0ppcGVTSGdNCmkzQW1zWS9HYXhVSWdQQzFQbnVi
            QW5yblkrMk84U1VPVDQvT3NXc3RtejQKLS0tIGNsMTI2clZvYXNrdzFaNTkyY09F
            Tno3NGZuN1FDQ3JsUnlYVHcvT01SbEkKUxbanRu5qIQQgUH/EVUGUgIS38c3NhZ3
            9+jU8/9NliWOXwNed8gbAdYMtlwhJotCQ5mcDO5B4x1i/7P3zCTg7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-28T07:49:47Z"
    mac: ENC[AES256_GCM,data:7ws/b5I8JEbYro/7hPDeMrKoi7f+2AVAphIQOe/i2k4wfrBrs8QkmtDUOmkmlqRA/uG3KcF9lXSgngYRxTzsGn/UvBe6chWWJGeqgpqvCfb/8UIJYbmh7U4x+wn9F5SfkWJPvE4rlA62rXkRm+ufJFv2nGuEUQCKsBMZCtKCbIQ=,iv:UxqIDXN3IPnE/ZaL+nqA8ERaUgcHQoK9Moa6wejZFXw=,tag:h7CssXZtWa4ECVlSezjm6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
