apiVersion: v1
kind: Secret
metadata:
    name: django-secrets
    namespace: citrus-dev
type: Opaque
stringData:
    DJANGO_SECRET_KEY: ENC[AES256_GCM,data:pmUCJ10hwzX7+tX6E4lrZv3G5DAn1NIcT6MJw0L0L3aMIiXTwdQRiV0JoF/L3/n0OptQ4MA2EUUC27ZmUZweWowTA7o0SAZ1t5EIh2ZQfZXlgIQ=,iv:+lJStK0nbjq/BYX65yCpK8TLxgt854883Wca77fZ2hk=,tag:Tw+unNKgNanAYsR+VYZOlg==,type:str]
    STRIPE_PUBLIC_KEY: ENC[AES256_GCM,data:6Zrfw4jkwl4cLrziCrCSZ83C8vXXM7QYZFDRSpKaSWPcl2XoXHiIo9GCXFLFFKWWXFmfG7iOe350eDhmR+lVyAag842cTTbnONQrjU2fwwuIqpgqDOCRqIZxUzk9FjtQPZjCx9FZaCLy224=,iv:QZ32uIDP5Rlz1IFOeHL84ZaioLOEqNtLpdwMh9+J8aw=,tag:F9n0Z6IzdVYQVpAO9fkkFg==,type:str]
    STRIPE_PUBLISHABLE_KEY: ENC[AES256_GCM,data:b3O/PI9qKyngZYsJwLaaFQd3wOmedy8KlM/n//4M1A2l0sscVIqRI0wTi98F2JWWuE3at+zxUHSj0E0ucTOeJCeH8GZ/X8kEY2yj5nmnvAIV2sPFW08LyXxsqtARElsuFdLozEXFE5+5J08=,iv:HHoFuR5tVcjsQxfMMNyH5JenScQJCWdzpfsRlvfAwBA=,tag:HyhmWOxiCTK4eoo2ZltM1w==,type:str]
    STRIPE_SECRET_KEY: ENC[AES256_GCM,data:/jzY89JvriTpb8ry3qut035vIO/nv64cmVypulX0xLkxiJSsQgarWaoIawVSJq0SkBpLB4LT85FWdjzh9m5bM5d+eBN89uqjI4HeWPLOYLBhahsmYC9/PPS9rFDQb+8DnXAKGIxj/MVwycg=,iv:NIThSdimwoXT05V82chV53XFlTaMQ+zGU3eErM/QYKw=,tag:GD7nE+7Hy61ow7aAAQcgnw==,type:str]
    STRIPE_WEBHOOK_SECRET: ENC[AES256_GCM,data:FRAGI1VwJ3aqZBzkHutE268AO6x98wuhKZT8Sq7GPrqKW/OlMSU=,iv:nyfGOU4m5o/uxejlkjTcO16CTvG4gO3DFuCCWRVRXow=,tag:0BV0iKwXzIk7f0HKxNxlRQ==,type:str]
    STRIPE_WEBHOOK_SECRET_DEV: ENC[AES256_GCM,data:Ad3eIopcMzUUROvaPPKl5M5YZeTaEpe3CfRgfO+HnGtSVpM3pbI=,iv:QzpbHIPHJxufLZ8/U7DmFMQwpVazLD4ErcclTWRuGG8=,tag:e5QSsxJ9SXURcMeAjELT7w==,type:str]
    STRIPE_WEBHOOK_SECRET_PROD: ENC[AES256_GCM,data:y2XcAEA8y+zNLJ3AiWZGGtY0owwGt5rGY5rABLAMTGJWNye/i6I=,iv:VuWB8bzqtBkpnw4Jwbb57i8hgLd1tSup21x3xH7qA20=,tag:AaExnuqPCGoAimL4JwWOxA==,type:str]
    DB_HOST: ENC[AES256_GCM,data:Tfy9flErjkxy+2jthtRNaMcXiiSjXCJgrP/+6KEu3sXMC3FdLvQ4kYBVZ6bKBUftR9ifQjrYUHKYRmPtrSsaJV+Y/dw4yRSbnygMy37e,iv:9hDnStp8ZE3/J0WFxJmm/SiQlO6ogQGX3lf7TIku5WM=,tag:z3bMRHr49YSI+Ea51DH48Q==,type:str]
    DB_PORT: ENC[AES256_GCM,data:QcFZm0w=,iv:cPJs+qPRFDev4CmpC266lpJVuo8LvHd+LBO9EjEHTqg=,tag:xOYZoBPBJ/svuYRQpQY9Hw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:QICvuRZNDv1s6Q==,iv:eCxzF+MUU26mUYTpEt3rhcV4zvjJmzRKAvRJcli3Spw=,tag:qoD53MsFdSDdfLiFvKnOhQ==,type:str]
    DB_USER: ENC[AES256_GCM,data:yiEr0y0NjAJKhNgVU/LM,iv:74m9HNYmKcfmGH7/RUcDwgszUB5Y2ojzMBAaFLyxVmY=,tag:KDXR85l7pJTT10SROPVHuA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:WcJzgev2qv5qsGLEn1tPAHNnPKdTgW3a,iv:gbPt0+g89qxp30IKQRwve4NNhNnNGnbGwBpaMH7yy54=,tag:3uTPJw6BPdVQ0/4s+dz2Ww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdmFNUExSZ0x3eXlobng2
            MDJvWHV5bm5HVnNUUjZ4b3dLTXlIL3lUWGd3CkduNWVSOU5SbHh4RVB3YVBpdW1n
            Q2dPZlB3NHdkVjRjNndCZldoUktlSEEKLS0tIHptWUdUZzF5bTNJaVQ0aFloQUNa
            VzRDTm5PVlRMVlkwdGtjNGJYUmZzdk0KPKmCCWXwz72ItTSn/BWTR1G3FjnXD+b9
            nJAkakQLLU3yzLFF3KYRb0s+jmsTOuav3OTji9374M7loDZ/GD2mVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-06T23:50:59Z"
    mac: ENC[AES256_GCM,data:+1XmXueg3jFQ+w7XNb7XDVwuB77xcccbJR+0saIJ3Bm3ICnsu++DtVzhDutE/QjRH4K5yjUZmJZIPWt9ArC6mI9rmBOawRnd5rwuPV/lpdK6sb92lP448WGTazVM6S/29VBwH9wz2ibextSZblczKUtfcI8DgZkZktLFPD4kiZA=,iv:deXEPXObtOjIlVDYlRZeRsltCAMZWcjosfh5SK9mhQA=,tag:q25tMo8JPwDR38zD28dLZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
