apiVersion: v1
kind: Secret
metadata:
    name: citrus-dev-app-key
    namespace: citrus-dev
type: Opaque
stringData:
    DJANGO_SECRET_KEY: ENC[AES256_GCM,data:8llXKhjxwrVg2raKBwGcf9wN2JwFKAypEjti5bDz4t6NPmhzHX8H4Ye6uSY69q27DtzVMj53UIASHHt+zRTRNppsb/ydGKJ8lQpGyz3exZe7OpOlF9n7Qc2f4cjewfZfWm/lEw==,iv:elncaZCxZlaUqjvdFmzhn7jaeZG2wsfxZsTdTaunhow=,tag:LwU21cSFjxjIlkHnwqQEug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1T2hrMGNpKzVFMk5UMnlp
            OThscC9FK0E0QjNZSW5KNWJ0ZVNYU0FNUVFFCkJ6ZXdTaHFwM1o4bWRCY3U5Q09x
            SHRpTlI0azZ3Zkgrc0pMZGtHQUNJU2cKLS0tIFdSMnNkdVU5QXh1Q1UrVkptN2ln
            dFFtSVhLSzVFelJDZ2dDT2dBOGtkSVEKfATPXft6eqymczBmU1w43wGZk6PqFenz
            JRSY0SMWRKBAG5nv1UZuLIKdTJl2Py4UiGvLSN07WehJbAEeculRpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-08T05:17:56Z"
    mac: ENC[AES256_GCM,data:1hFMMehoCnKVdxwBtL3jV5HPhxIIdF1avG+4EhE7QYktJt5VSlSo3DADxc05KmLHQ8ugt/USe+rqehW480Mx7l/zzQj7B/Kwgq+kpNp0kb5t6zR6K6bWAQZIC8x4L/MJbS2c1zdRlKyWCjq++LQen8l5dGpk+e/yKivp0SOuDFE=,iv:hTi2iHfC18dV+ITfl8Tx9/sqYIm1L8iP8WfJRn8gCEo=,tag:Wq9b54vFClUUazAHvEcznQ==,type:str]
    version: 3.13.2
