apiVersion: v1
kind: Secret
metadata:
    name: django-spaces-secrets
    namespace: citrus-dev
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:bD1J8U7JsAcOTld/3K4OKuruluM=,iv:bHhO0rcsIf278o/idFBkDcINWpQHxuDQeVWVgMXVspE=,tag:cxlOjTUcqwJ0Fysvnc73KQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:y4YMIeMoQAfqaiqW1X6e+3yB2pZnuS7pahAp6vuMgAArJLAwY1L78A0iQw==,iv:F6S2qnoUtVZRaFYNGIFCqoE9iazD1Upd+5a6Lu3WutI=,tag:HQIMRD9rWaGeC4bNR3CbFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VmZqVWdYb0VOc1V5cjVM
            R1l1dzV3alYwNlpBMUZ4ak9aQW5Ub2M4bjNzCmdFM2QwbjdMaE1kQ2trVjQzMS8z
            dFlNMFEyZWRnV1JBWHp2ZXZEcHlhbWsKLS0tIEFrcTZYU1Vld0NzakEwZ3RhRE1L
            WURaZnJJeVRFQlg5VWxDbEJ5ZUE2bFkKEqhuDmfhVNhK2RnlMV3PoN/qMwr+TCJ+
            YrfG8MfS7WKT1i22iXBnpIGHDgFN1vXEfmiFBGprTme4oscwtUxiyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-08T06:54:40Z"
    mac: ENC[AES256_GCM,data:FQrLpe5W4TrzYvTRIrw4oY6rnNa9Uzo487Mp9Pf8UKb5cq545nFAKFyiNI0vocuwnX/HSaOWcnFkBBa/pQRfSLbPupp9L8Uo1h/0//AaBgdRx9fOLn4/gXqhHlzqKV2R5fVFqswsUbkX8zOKSCaNyAo0xPk45WBTAoWUVYA+07M=,iv:pmyf96Pn92v7KI8XDbNzkk9WxxNXE3njRrAV5IeFvwQ=,tag:VODkIVnjr/doyrmt7Dqzww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
