apiVersion: v1
kind: Secret
metadata:
    name: django-email-secrets
    namespace: citrus-dev
type: Opaque
stringData:
    ADMIN_EMAIL: ENC[AES256_GCM,data:VB+mhny5wQSE2v7VbBeYzMfa6pVd,iv:Jz/lcqsZxvBtp0ywOIlsdsI0Tp99R++5vn2kxv77VnM=,tag:dTNmZg3rj2ZU/xVj5+26sA==,type:str]
    BUSINESS_TIME_ZONE: ENC[AES256_GCM,data:WtnzBiFpP+ML3SPlWEUA,iv:mdlfoGs2T1olzowIcDpryGktZAMcBofZCDEJfyEHiNg=,tag:+87xJvK1Y7+FUVLhL2pZhA==,type:str]
    DEFAULT_FROM_EMAIL: ENC[AES256_GCM,data:AJ03VU7Wbvg7RVOYt7lge7o5FzuQF2E=,iv:3Via1tnFfNoZfO09aEpa/yQc1b3VcbNpKeImkylVDLU=,tag:FfUfvdykC7UU3Yf9/8UU5g==,type:str]
    EMAIL_HOST_PASSWORD: ENC[AES256_GCM,data:NA41FB9vtoyxncOUDP0JBw==,iv:gpJNuvfcGc5Sjzc57AoedigZ95E+cHyvDlRTf9lngvA=,tag:jBPVF8AXXPmVms1cLk2DJQ==,type:str]
    EMAIL_HOST_USER: ENC[AES256_GCM,data:+AV8IMBflhm2wPEdatldRCa6HDi+eiw=,iv:JEVPM4F1OKp+o35mR0LiLYIiQTE9hIuIIirQJRkML6c=,tag:fkgVzZYrjYL5fAeCHqfQEA==,type:str]
    HELP_EMAIL: ENC[AES256_GCM,data:qzkAMkj+yEv3UcW7MTEdVF5PeI4W,iv:JdS4ao+lefux5gD3SIkEYSJLcGlTFFM0F0ttKQ1yt5I=,tag:TjEZyhAwrjSv5tr9z///Pg==,type:str]
    MEDIA_EMAIL: ENC[AES256_GCM,data:+NQugVGj0cQDZb4lldTJ1pNoh3OH+A==,iv:Fnc/S+qXYzzRilOwN/POld1X3gBG8iVvVW0HVNwdXdU=,tag:EA69qrWs7OJ2Sc/VIclN4w==,type:str]
    ORDERS_EMAIL: ENC[AES256_GCM,data:91kdfrvFE+XEPt1VEbaD+K8SNiFRB7w=,iv:pbSB2zrQckCy4m7oEx9SIzXYnMUAArjPiPR6U8nKovo=,tag:y1CwB/3GP+2n+poqK92Obw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TUFVVEZ2UjVnOFVBRTRo
            NTlKL0xlblhNTlcxUlhYTmdrSWRudkwvTGlZCnhKOUFrWmNXem9ac3NNOGxJWURm
            YWl3Und2M0ViZ0ErSGtpeHQrNkRCeHcKLS0tIE9lbWxGSEJXWlREem9aUzJqVExX
            OHgrUEhaaTBScmdIRTkycmt0UktKa0EKRNedgG5i3vIw2iPZ4i5WHa4SYpH5cjz/
            AMevmK5mrSP27yRgfp2NGcs222PYmopDrpyix2uUxMfbzpdvs3Elhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-06T23:50:59Z"
    mac: ENC[AES256_GCM,data:imXvhjDfKT37XNpU6CVH3UcXBwFph/OfJIu3DjBsVIMgg+oxnJtbBH9LboGZA4sJHcPu/XX6afnHJwBkDEiL5IK0zglWPZxPr7q/eQc8EDLh/ex5noslrwUrBgePvEhXyLlc3+FDCAKfFBPuk352eWZhtuY78ud53RyiEW5t+rk=,iv:Wdpq4oV8r/oXgwtK2K6rzJw00PReeSxFuNwWqewF7Hk=,tag:1CVgB/B/K9eUqADnkHCrwA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
