apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: citrus-dev-secrets
files:
  - django-secrets.enc.yaml
  - django-email-secrets.enc.yaml
  - django-app-key.enc.yaml
  - django-spaces-secrets.enc.yaml
  - citrus-dev-payment-credentials.enc.yaml
  - citrus-dev-sweep-runtime.enc.yaml
  - regcred.enc.yaml
