apiVersion: v1
kind: Secret
metadata:
    name: regcred
    namespace: citrus-dev
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:olzZmLOTJZvh5Pv4rYXtb9Pi3xEzY0+gWS4oaN3CpUIimUrjJGEhqwe6hUPuvPdVGL6K5BEf2Ipwcp6h5FnawgX3m5tmVxRXwh71J172+3yEScGldTmoQdKBdTIAkdfk3fXeFIdME6+VK+C9o/cjw4zorBxxf11/XXnraPJZ4mvSjL3899Jgq+O0G9AbgcIhx2Jk5r7Z9kU2X4ZWrcMR4xqIQLQcekfAOY/zTt2IQbE/Y0lfnqggUd7XS/LN8YlKPYhFt2CyPxmWrScsoEWinC3qrAk5aPusTK57tk3TakvUN9O//UDmJFdm8l+YDofNuLTY5qADDYWlGlIQNGUOillB//SC+YaNpBOzw1qvuskUCoRiNgBfPRREKOdUCbUsfgkUf9O6cMFXVzkXARoRknZQw5rLC9SDSVdiK3xS6e0XKgBvHkyfJODw8sF3MmlANhKDeDsC6JJ4JXxh75DpSUUWeOH3UZF23TXyd68ogC3eSDnXdFw7zyVTkkvvzBziWMYDCRfpI0qOuXMZuJHy7MMLHarqlmwMRh+uCAf2cDmv37Y7ioh7qsALAAWTqFfI+cm7JuYor1OQgeydt74XkhPiDC29q9Fg+x6xRUbj+1T4qHaKZjgXVOvT3ca9Gtmm4Ytea34IK0R/9TdDbQCrmiR1VxnCG/uuAaDxtFMobXir5VtGFf7fch1hvSWUv4ewtMAdigv52aA3cEdK8wsf044kKHVFPQZcT7eawRf9L+CWNSEmdCZldh3SIvp7pQ4gQWIbfTyw9DOs8vJu,iv:WcuVlakVjVR8UPWQGr1lQhkdS6CsIpQNqwMEKqq+Efc=,tag:aFyIfSoKwOsciPcm0b3txA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QU5TWUN3UFYrWXA1QktW
            cmVzZmx6YlBNUTVTZmQxMFQzNDJ4ODBYTjJBCjVqM0VIMlVVazBDYUs2bEs1NGVH
            ZkxZZXV3OGxyakc5Q1doRzBHQVpPbEUKLS0tIHhKQnM4dnR5NHppU1BtM0ZUUTFi
            cE5rb0M2eFdRSjhoNkExaFhWT3hlS0UKxEZYPInkCZZd1JZdu2PHasfQhVJkFhoN
            nVxrwLwEokHYbjXOrM6IsHWmmjIJUl8aUq9oa7fNpEnoivkCIIsoAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-08T03:58:23Z"
    mac: ENC[AES256_GCM,data:ZScoJ1AszceL3573x7F+zjEKfQYIxAQM3OqU90ihR5PGQsTQC1wSiW/oHKJ50yfuPQeuLnduEW50TPK2qWg6SGcGYqlZrCKnvLHooZkbFSnhr3kS7aoUV4KXCAoBreHTQo9o8EA+sg8U7lcbh24l/9+XB1J/nXsdozBGnK2Ccgc=,iv:8evt4Vcl8QfMcnL3mqMFqqClb5f5yXO0p70a+S6wGDg=,tag:FCk6PyXHRAwcvb9liiyoHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
