apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: splattop-bot-agent-8s-secret
  namespace: argocd
spec:
  project: splattop-bots
  source:
    repoURL: https://github.com/cesaregarza/SplatTopConfig
    targetRevision: main
    path: secrets/bots/agent-8s
  destination:
    server: https://kubernetes.default.svc
    namespace: splattop-bot-agent-8s
  syncPolicy:
    automated: { prune: true, selfHeal: true }