apiVersion: v1
kind: Secret
metadata:
    name: teams-refresh-db-secrets
    namespace: default
type: Opaque
stringData:
    TARGET_DATABASE_URL: ENC[AES256_GCM,data:NrHmXloI6CTJwv+nCVpbhOq2FhMrO13nVeYJkgOfdVsJMLz5SfpZuRn0B54mcqagbw18HE4v4mikV4qmuewqXnUJ4YXYNL8WpiJeDrXT4MfjXTvqvRvxOcVxR2QCjls5BsING8POtnAP07r+WSGDAC9b9aXV5BZJD43L6yr6SmyHJzBQUw9uMR2ES9UPzgeb+kW5zdt2xfOLvePMLIHCNMQ0pHyXJvXNd0xhJq3m/qRJqNs=,iv:DAxgmI0vvjJFkMTCNxONZ7q2RdBUQ9gfKNE3o7A/y8M=,tag:2+vXeiJKD84lR5W+zw7uCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQzFld2NjZ3ZpRm5ISGI0
            cEkxRzZuTXRtRHVCcXQ5aTlMYlNjaU1ZK1J3Ckg2OGx2cU81elowME5aL005bFFW
            YXRQM3FreExpMFo0bjdVbUhUT3FYTUUKLS0tIENMZmRzR2JpalVGekxSR3lJZDJL
            eitTWFNYS2dqV1RGMGs3NEgrTnBweWsKBe0BVzWi2FC/nzGwmUyV/RCcVfTvonxl
            14P5yQLR1JIPYtPP76WYesooI25BHMBGJ56blNj6sK50QKbFPB1Z9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T05:12:30Z"
    mac: ENC[AES256_GCM,data:pu6+DCZ0BaaqFdUNyBzmdpSxzubf/UkU8YoYaE4e82Yd08TsNvA/BPvfIbY2TH0fDOMASHgeh4HnnYcMkGZ/n4M5LRwS2YZsd316WuSlxzCd1j3g4HTyde+VKBsI9/4WLePCh29oETB7R9MlLRYfKf/z5eQ69kgILxJCbqqZHmU=,iv:w+DSkZgN4eFTN7g4Whiw1TcAsk3V3OKlJ19jP7/w14o=,tag:l/xaHKa/fT+1G+rvJIshpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
