apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:o0ds7UME2koLt3//5q92xcqs+OH3aXm8XErVqMXKeuZYLGo5RMeMrrj2AY2C01mMuEyvD5n+MwRm8l+rgcU9TrtWzpgE40Yqmyhh4Z6ep2/mjUUyNWP+kBk0i1wIJ456+UBs3nHh/49DqLBur0lz8ddhjrWejGZswxr5XtNs0rykKokGs3cQ+eilY0L/kXNUvnRXnZlNuIDhxJEjF64KKl7VEhXLHXz84b44R4y4GlWsmUmwbaj+XON7oskdYRGvNGIEtpZsKaFZmzUBo5qUs1x91glgv3For8wN472S3DjwZTHIBSAshCHLViufe0dkcSQhNPOI0tUBYkCaR9J2KPfTEStkjV+cwB8BviLtup9ODrR2TTgrOJozhTGYvVQOzDE67/UP7pERluytNK110v4qrpmjmmuvxTHiOBT2Hnzwh0yZ6HPAwpXBcvTOCi2620D9aAgQWgESQMxVDwpI4pTIAT0+wKpFC4cvHyZdXCnSXXRv3w8IyPoVNOTiVHdITLAMRbIB+otEcTyB+Cc413bP7eN0wk+sUFbi0/xB8WEv+H6urMQKUuYo6CsUV8SLmkgrE3umBU1phS0V6EtFiH91att/jwGp0VahadgqsCCDUnWC+czBXLdf07I85CWsLDbPx+P9cBszERhoX6tLFzTfLyiov9UWD+wYynutUN+Z96/izeKsEXH9zq8haC+KbWDJaPIa79AXtj1JQMR5985S7qt8QvFFzXeMwMixWOIZMcVnjgJjAqntRslK+HLOo4JUfaBFvvDSV2Ym,iv:giRvb8stFwT4SJBpLYMcfOYkhpJoKVueBeSPwfRo7wU=,tag:c47agKNJBADARIRh03G8PA==,type:str]
kind: Secret
metadata:
    name: regcred
    namespace: cegarza-blog
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseGFId3plcGNrTjJMUE53
            aSt4cUpqaTBzMWx5dXhzSWNTY2V4YkJycW5BClI2WmJYdTM5b3FFKy94VktqaDV2
            MmdFNU5NY0xLTzZJd1JDV1pSSTdoWHcKLS0tIG5KRWh1MEkzLzlxK01EaHVJSE9Z
            eTIzRzVEZS9td29DQWl0WStLMy9TOFkKrNCkmh4AxyPINtNi071CywqUWfOHeZAJ
            K/Ij+VIbeGYSzrZbFKQrStE0qAYIzd1xydIHwFlybm/N9td5CFPVlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T21:54:42Z"
    mac: ENC[AES256_GCM,data:BM/HuYvqSiJ4bef+zMLn2FZrj1/tYdGplw0QCXggRCEbvMRny6+Wb63v527XvYjEOj7AO3013UP0nofxiOCILRjJK4ncfcea3mFX/yDF4S+h1lOWaSZFaZbN4BbL5QxX+1LTC1aRxDDBSPAKRPQQjPk2QV12ATCE5+b/ficSsQk=,iv:kfPzvmGHk0Oy7M9JAu/JxZRyFyX5ZsNpWqKtKfYwlEQ=,tag:ZIvYw88XL5wSt9dUvKVlLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
