{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "citrus.fullname" . }}-migrate-{{ .Release.Revision }}
  labels:
    {{- include "citrus.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrations
  annotations:
    "helm.sh/hook": {{ .Values.migrations.hook | quote }}
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: {{ .Values.migrations.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "citrus.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migrations
    spec:
      {{- include "citrus.imagePullSecrets" . | nindent 6 }}
      restartPolicy: Never
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default (printf "v%s" .Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.migrations.command | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.application.configMapName }}
            - secretRef:
                name: {{ .Values.application.secretName }}
                optional: true
            {{- if .Values.application.emailSecretName }}
            - secretRef:
                name: {{ .Values.application.emailSecretName }}
                optional: true
            {{- end }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
{{- end }}
