apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "citrus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: citrus-web
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
    {{- if and .Values.media.enabled .Values.persistence.enabled }}
    - name: media
      port: {{ .Values.media.servicePort }}
      targetPort: {{ .Values.media.containerPort }}
      protocol: TCP
    {{- end }}
