apiVersion: v1
kind: Secret
metadata:
    name: bot-db-readonly
    namespace: splattop-bot-agent-8s
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:qYq7X7l3rz2n1nI3FZtUAgICJr3nTy7EwJkmqmxshaDTKsUbfT4O3wBMUOveIJ5alsTIeU2thCFwgNtWBpAytNygKi1NY8TMrLgaOGoJLbk31uvabIs9i9JkRrKVhoh5tdX7aFzq1Ovf8g/hZl4lcVyaTKgxVUtv0pYALbBezDXhevpXfTEL3sezSxWj/7a76OdwNUDD6RSO/jtADaiO3bG1Tzet4Vu89CVQynFM,iv:Z6dgZFJ8jWLDpRUojnRfOQYLvZD852+lZ5IpV8mYZU0=,tag:/P9ANmSwNMRkHZ+YFxpG9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdThodUZDVFVRaGVMSkZr
            NHpCNFl6QWo2WjNUSlIwanF6ZStEMDlwK0dVCkpFNVJNV0NXeUVsekxOWHZ0VkpR
            NjQ2ZXdhZkg4aDlkTVZUbmRlYU5lVlEKLS0tIHNIajlkSHBVMlBObFZOeDNZcGhy
            Q0VrdStmZWovR3B5dytxRkFFRWpXTFEK1rcmDSEZca1wVWJJPBB6EVMfgI2HCQYx
            Qc7PV+voG7Eqrii/ERRv3dA8woUFx6kUQQcFgpZdG5ZASCRtlYtcxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T09:30:16Z"
    mac: ENC[AES256_GCM,data:h560wLRisQjRc2rMW5bwILcx/zo0D0bnRv1NVdzrrbEmW/IJXZrYqgAlGROcPCivQfuimsxOj1G4yglXAVMP/cDhr8IdmfQ1fLhKKShG884b+K9NzZzO0zJbc3LQtSi+6zzQqBDnCEY+gNftrGuxljP5MJ6grcsjrsm+Os4Zhes=,iv:OeEeXk4I1hqrI0Qza6wX52HLJW9GxkRHj1hLpNONI2Q=,tag:8wptv4S7iuLJnYzFbEiG8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
