apiVersion: v1
kind: Secret
metadata:
    name: bot-db-readonly
    namespace: splattop-bot-agent-8s
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:PiIJOzgyvF5xYic9jwRFny+OIhQRHuZqCsa5BSZOvJpxMDxwy1JMJu08zE5uGHWKCIvOXyVGvsVqc6sAsJn/EmGkBn8Vb6uzjX/vW5DZQFLfozXN5TwyS0l2BemnP0F0pLG4/8f+rcpT8M/z4I4eiINX/DqtAvFSBY3omws7aSyqPDk0td6Lzpy4ZjOSP0DdTPGNxJjbi49CTIYLEdRFSfwT+jDuFs2jPjKjcROH,iv:4CYx6Y1zn3Etm0u+wIEf6TKWVbm22OBPKMF3XKnF/y4=,tag:bKfg78YJGWh0xF3qblZG3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBd3dYS0hFZjIrN2tsMHpu
            ZG5pUEFMSjRUQ1RBOFhIVGhlNVVlZ0REcnpnCkljMklWL2Q5bFpSZXd3UUVsS1VT
            T0pSbk1DNFZEWHl2dWRwWHNjcG14MGMKLS0tIDlueUt0UmVyeEVGTGtObDhyNkNy
            dmNyREI0Z0JmUStyU2JLUG9xK1Azc1kKk/C+V4tY9Pooe7VszY8/wIjmSvO/dH0S
            /5v/RbeVsVEKOh/CEVTuLReDoAjM5W0tjobp8lTaTooki1s2hi5Z8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T08:03:11Z"
    mac: ENC[AES256_GCM,data:oMkJY7SHYlI/RWiJbTsLhR7MdeLfdclKcKqJci+5KejuxfXEWqMxBC+bNfUBEyH/gqt4vx76ASh9P/eA6lfWnVmYfR0sj1UEtAZaB572Lxkv4k2SgLP1atEiy5BhdLFaYnn6yy2JixGE93FnAQFteDPa+nNd3imuqiSXD6rWbuw=,iv:ogf04N6FCV0/gf+zUlBFqw1K64RThodpQaE2M98SZmE=,tag:54ri/6LafbIuImT5vys3xg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
