apiVersion: v1
kind: Secret
metadata:
    name: bot-db-readonly
    namespace: splattop-bot-agent-8s
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:IfsljSjxw9Sz69we/z0mF++5qPdN5kiRBiHOQzAHztLncPrh3/7LGaHpAz654bDre8+I9C8sbfT8CsaOiIWtaQk5fvKv1mTE+KIjtF7/92JYhUHx2bDUl+nUOlXRary61mO7bhCBzzvqwslIbN6oH6vfPWX6gixDJJ0zso5WJ746LttZjTzkIK7vmuhCZDN9Frc4Gl5nDxcsUPhdavvoC7J6jl20UgK7XCnB5dtC6m1j,iv:kORsE7ggkx9uJiJkq+J/iObEfnE094FuWIsJY7C72+w=,tag:fo3j5QDWDjP7W+vutQiMbw==,type:str]
    DATABASE_SCHEMA: ENC[AES256_GCM,data:jupkjn6OzjWEZpgo,iv:0AhJXYhdKNtxsXvbvX8LJKfV+6Tv5ZDLtA36YOiUIrI=,tag:9epdPCPq2yGUvjS2bU1wlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVGkzTDlyRktTU2xHRGR0
            Z3dhT09seThmQlV3d3ZSN2tmSHJmK3AvUkJJCmp2TDRDZ1ppSHRadWdhK01sQzhq
            V1QzRlpyVTlGSTlHNmkreldDTndpMjgKLS0tIGRRTzNKU1BGbUNibUtSRjZNQmpL
            bkZsdFErQmJqWVlTTktWNm1ocUlwTm8KpWAzh6FXt9UE4Yvp+JuYzbBUdjxv1n46
            I3MPiD/xSUSkuYQdR2/Rx5z+PSsj+6WiAJWza07sYc2epAGI7oRyaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T08:59:01Z"
    mac: ENC[AES256_GCM,data:op5KjyYK0VKiA6H+nix5ubYbaoTsdvl2BoY7todTqp1eHzFXzfXpK49ZBdGDzjMIZPhBP14p5dZs+FBKkgRyPLtPY5s0A6VtLRAru0/ZEIZGBl8+uUWv5K8mvuiZt+fBb6zF59otiSUaOsyfRhshk6yuZgTnkikeVlufH9u0syc=,iv:ufviNb3766f1pgvzULKLcqcQBMYgF7WBhhOf3rD5lpY=,tag:bKhzOQ5eM3QuWwxuX/FbFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
