apiVersion: v1
kind: Secret
metadata:
    name: regcred
    namespace: splattop-bot-agent-8s
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:87z4Z2k+fOPPlqcG5xhSLycXdQjT1/qogto4QVAJU2qAsb+UXOmtEON3AVITJFQxIB3avngHdWbKEBWEk7PfIf5stmZxwntCxVmZU01Z8CzbjtxHPt1u07vmLDmIH5bnUTnwxNdvZ0rclm9DeRCKmxevig03UuJXrSqgH8oQsTgYZtFq70YmHqbUuaZqPccMWb5Cs5EM9SbqxmOlJe1T0Yhp65/SaguC/3fO3Jz11TxoSnKOQlm8VXSZAsRiG7yOx2ppBDc/kymGR68C0uuBkUN6C+ow60YsCwpk66DhFir55I51nIt+pT7zaFUzoktuqTwVEEIyRifI5b9wxZOtx5a9ktJ8zYl4WS3W8sT0rXuO7tczBItOQDxD6OIryf/Y6ndWQt7bFBvKxhcdaNlaCpO4d5dE8PvHc3XTq0RYhOHPBUgPjft+OtQfwLP1koNsVcz+xtk9nr4UyMdKfEi0K0gVfCdGT77dyU2xZDDPp1BOqd0xTnXwPDyc7s4duJ2dZUaiSQVHV/F6pQNalmQF0ELATjz8xJ3NkT1V/jcfD5iS7hH+/JoXd6EhndRQf4rvVr0ipJJXNtJfVe+c+vn+e7gOzEt9T1Bfbdj+s1WCWgy24QVt4ed5MtN015eIIbblnPeXLg5o406+sxsKqsahUidsoXovhJgNFMlWbE76FjqI4Exrv0aR0+Uu8eo9CEDqsyiXbhvYSwEzvh3r22DzkVXTk/uO0hqaUQ8jK5d4Wq9cUUcDKcuxr6jnhxjh79E6fMMsFr/Fo47q11aK,iv:+U6UcZsLZ7RXjLamicaYazXaj17j9abSxgE0VwitV8s=,tag:4YX5Chg73aLgCmvnxVgv7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2V0hCcW5EbWMzTmZGNmdG
            d2J5RHp5eDNyOUg5cWtqUTBlMWZadUNQaEhNCk1pbHduWGZhRTV5NG5MVXY4am1F
            dmhCTklMa0ovOC8vME11ZGY1WWI0akUKLS0tIHM0ajhIZE05T1AyS2JDSkZ0b0xk
            NHk5djNmWGZ5Z0NraUpUMDA3TmptMTAKanEDPNC5cSSSy++pkH2niaFQdPLYZHXn
            enVe3heS/RyqxQGNr6KcTDHunuHgh66PtkiN3Lkaj28JyhRLrLtPeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T08:46:17Z"
    mac: ENC[AES256_GCM,data:hK1MDLOmG503Nzmeb2hBYpf3mJjddfJsq6KIY/CtA2A5s9dfGphzakIoSeZLtD/yW6MN7IdJtykOD6f9ndVpbMx3jMGehpQIC5K7JAZ94n/wUy7jrkRMLYy2NyyGmHGj99joNQj9tTD9QXcHNyrQ9SrE38qYZBtOeRNghEokmX8=,iv:ZteIO1sXZ1iNk+zErgKSYtSx3PaFk2z66x9kARaIoHo=,tag:ATs6KT1BFeCU3rmdkDdk8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
