apiVersion: v1
kind: Secret
metadata:
    name: bot-token
    namespace: splattop-bot-agent-8s
stringData:
    BOT_TOKEN: ENC[AES256_GCM,data:tUfap5mQVIt3ZGECzIhsPDQjyk9yzYF92zsITHdrh7wiKzc69fK+jnmb+Z9qF//aYE+uIGLvOxqA488wOE8ugajseFZRbD6Y,iv:zlJxFpKoKMgIJgL4+BQtI+CYZ2f7z2qC3HM1VaJJals=,tag:LLGqwxsFPcEQZ12RGaCJRg==,type:str]
    DISCORD_TOKEN: ENC[AES256_GCM,data:0JxLn1gdxyVjOsUIVaEkpCWlMYGIoIkbqxLP9Ncx7PXWPhwBNdWY5EEWNaj2DJiTVZ0+qy298hHh5aVkT9rXwHOzJZRBy8Cx,iv:xYsjYSt66ASxfAp+nlKjOwoRimoV5tdc15NP+tRskts=,tag:N/7AshIDQJ2cuIKb4kH0Bg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdWV2WDdiVkhIWjUvekdU
            TWY4ZVNkQyt5RUVFeERNNUw5R3hKeHJKdnhjClNZWmJpQTNyUms3VDFJZG9VeGUx
            RnRURnpSTGxBOWxiWGdVSXp4dXhkd28KLS0tIFR6RlNRVXNuTnlhcm43QzlJM2pC
            S0wwMUxmTnZ4cVJlc0tsNFFoSjdXMzAKCqHdonkcRux225UMBRfpCZxk1sCjEw1o
            nSTzrVVqdjrLzL15cU2blgLXP21pkyq3ON6NXQvrzufJ6cd28oK9cQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T20:33:30Z"
    mac: ENC[AES256_GCM,data:dYq5sbac8Bd4L36fM2FlAKNOdoPdFQH61V7IzB7jorSL4t/mB0EB8VgUd95RUUnrxZApg+0KrasGWIAv2z8q8hpLwVMZEClRr8Ii2CEW8kc8wHqRv8nJ5GLjUUnmu7+Gu90jTbfNT5hirzTsNIO7/M3/cWtGTQyev1j0RkIKXdU=,iv:BTm1sM28XFnYVl4NkLJDF64dpXTppM42Nni0jAe+YlE=,tag:my3ifdJ06DSUN8/4PHp6fg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
