apiVersion: v1
kind: Secret
metadata:
    name: bot-token
    namespace: splattop-bot-agent-8s
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:5Tjofjw9H5U9K+8vPTN9CJCdsaUvCHToZ+TiQE1dF8YP8srz1Y0FeWNxsg27PdEQ33dEFW4sl7VIjbd0jQTlOrwAhwO2ay4+,iv:BB49pHScHoqYNqJ3ANFVD3aLycoypT/3t871bqg4Yck=,tag:AYp7tKex8lR91xIxSzIRUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuM28wc1R4S3hoSyswOE9t
            Q09Pc3M1QVVyaXk4NkJubTVvZWJRYlZwQ0hBCkk2d2NtY2prMjV4V2R2SjV2QkND
            b09TenBFYU5XejViN2xHRGU1bnhmS0EKLS0tIFJVNU9JVjhFOHl0NkVYbmxxbVNG
            bzJkY0F0WW01R2htMmE1b3lxVmRpeUEKe6x8Wqwd9O3PXNkgfFwpPa0gO12oBcoq
            +BEocZqR2JpY/B+GWabaoQz0i9TTGe3JQz6X0tm38zVLmofmxCK5nQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T07:10:13Z"
    mac: ENC[AES256_GCM,data:bT52zeEJI8wDIiRBCEMztpuJeOEiaJ2tNvrOw9yNwZ8Ab3qVo9IA4m85KtH9pSMJZPxyH0VtLwrpjYS0N1sl6UCG891M7yJyYn+GERy8nJvHS6VaLykR3FIkPQonI0X4IZ0GduNgtMQHQT3zwWoHSAK1Wt3axRWsu1l3oItsPOQ=,iv:wOjmzlsLITwzJZuoDd+2gV9KXhU4tfd0FxtY8I6jkOQ=,tag:h2Kuzmu+sjJ048XqAMIkRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
