apiVersion: v1
kind: Secret
metadata:
    name: bot-token
    namespace: splattop-bot-agent-8s
stringData:
    BOT_TOKEN: ENC[AES256_GCM,data:B9Y2wti8NEADY8Dg4uEbh1Yt8mJhtG2/dX3O1WM+AXyfSNrh//neoofk+AtqA/Lc4j5Y5VoTnHlrSzMpSD8EQkt7HBI0wUzx,iv:Mk/aZOeQIvcryxOOF0rt2/53LqppT+EmLbcDds8ZV6g=,tag:oL8jXMXKismUjl6g7o9gJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQ09GMUFnWUZ6bmFEZEZI
            Rzc0UWNpZEdmeUR2UGNQV3V4RExWdmhlaGxJCi96TGk3S21ZRVBLK2dGcHFzY21R
            U1pTQ1BxcEV5QnE4K1lQV01rTFJhU1EKLS0tIDlsS3Y0WnRJRDBaZEN6SHVwSUxn
            Q05OSm44c0FIdmV2OCtUbCt4ZE11bFUKlacZHxqB3DHzVDikJlcuHvHDygI2Ko4K
            Vez4RAFIehHKbj8N7faiEJDuN3/PuP4K7R0Yad5hxG3OdMCDW+qukg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T08:02:06Z"
    mac: ENC[AES256_GCM,data:1PjWXkYYXCmPyEjECSBlvzwEhTjYT/th0U9slYVIaU7aPd3tlcE6/KNGwXUn1YbaplWjjhgSEcDeVZHVnXo98GBYxG+g6neo0TXj0CE3sSyDFVl9tRl4hxOAFApz0Rf26ciGJ+RqFt4qHD0sHESRZAa1Fw4APQDXTc4/kcTNXpI=,iv:S4on3JotAIh2CiozvYQvM/lXpfuCXqfkTmjP5n62FPk=,tag:Lxa/ESzmKYlTBRt2S2H2gg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
