apiVersion: v1
kind: Secret
metadata:
    name: citrus-app-key
    namespace: default
type: Opaque
stringData:
    DJANGO_SECRET_KEY: ENC[AES256_GCM,data:yV7pVlOH2TtvptvgJUqQon8XK+VGup9AOdPYCQRM6kIGNLkC3kRBKyTFWM8G0+xQmp13lsBejZXMeGk4yR7EdHO81DTvhFw6KCMJNHd4/d5Rzd/OTAKvfQ+Wc7LLZHjv6tk5cA==,iv:pVEMfKAww/eTImPiTbQ29nUuggRpdfNy6uH5bqA0Dv8=,tag:+vGaN6HkKIcWBrA4Spl7Gg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RkVqMjZVNng1Y3FDa3ZF
            eVZkNy9DTnpuOHVadXBkYWdtWVhJYnRSL25FCkEwcDlmVGpoK1VMbE9CdkN4Z2Y5
            Tk5HWWlrLzBCNnAwZzZDNFZJZmh3Q3MKLS0tIDJiMDltS3JyTWJZT3ZMbU9BcC8x
            djRDQ1VYZzhwTlhjRUowditYMGdsVDgKbcrjAwzE9KUegsJQtRo5C7rXjhgM6kX+
            Dst3Y5jWQjUAhQ2+9Mz/hhXOGulHCxkUudsvTYE6tHO36dxLx3MXhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-08T06:25:16Z"
    mac: ENC[AES256_GCM,data:7ZWe6HbTUtXBzT30gK6zEBzBOqTiQ5+PLBiI9KgXekZar1ssHeiAs6p30zDzWVzo4X0OtakehvWScjWTbJwXczWbhxsZjRMt+oOWyq8eurENoL7uQz48I74B6VxkcCYEwCtxMJgCXHYKV546SvV4UfGQBflxsbq+CvUtLJbeSLM=,iv:KRTQH0j0uAdO8XPTQ9y95xWLHbHhu3/AX0RyN2EpYtU=,tag:r6+1FU9B6oVeys7sgSdtlg==,type:str]
    version: 3.13.2
