apiVersion: v1
kind: Secret
metadata:
    name: citrus-prod-payment-credentials
    namespace: default
type: Opaque
data:
    STRIPE_SECRET_KEY: ENC[AES256_GCM,data:w9OqLpD1gfguSrvhhMutCcHtrIxhuh7YA/Gu9+xznm8prxswuu5TYypUZgbl+xzWVmyDKsTTJ8nMUDGfmAcw7yynIrDTlvzlmSf3+2ffvDL7UG7dT9ga9i4Iytbx0l1t5uIYitIksk4Ui8alt3MNr3nkIMNuhwWgZEueUpMiPSA5skqo+1WIODLXLKEcWg3M,iv:Bsy1mQHiWU3jFxvssBGzZhhsn6iyItSr8uk44yz71L8=,tag:n3XTkWKz+bc89RAqGbqlfQ==,type:str]
    STRIPE_PUBLISHABLE_KEY: ENC[AES256_GCM,data:1/gTR17Crngw7WTtU7L/5Lbg7cgi7xkIoCXpsJSQBRZqxlJR94vZjHXrZAXX8AincI15+krFQEP7+4KFQSGOoJ0oHof6esh75KJdUIe5W2EVO3ZRpNmMcoNwysO0cw3NokpVTy1yyizLhYwRufVRKbnevtvEb6fa/1gOWViktRAr4Yi6M/sk6qqlahkIV/Du,iv:xRF2GDkl46Ql7OPe2pKSssuVFDzUGFTiPCGm1BGp6CU=,tag:nnkFjrIi9/CXfyojwnGllA==,type:str]
    STRIPE_WEBHOOK_SECRET: ENC[AES256_GCM,data:Us2Ue0f2cHkxabxyxoAwdcpf0pNjnvMvjFnYkSIVRDGrD12wXvvxtynNbp6KlzwkpLfyZg==,iv:3csCnS3ueqSjgDUhOrr/b+U+Ja4rw2i7kX33jUs8utI=,tag:9t+1A9uDdHQquDfGRahSzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnK1JpQWpVZmVtd2ZjeHlQ
            SnRSNkQ2MjFEQmVobkxYeDlscE9OK0k4TENjCnZqa2QyV2xEaWNJQVNrQ29GaXdP
            ZUhmb2gyc2RYbGhKdUE1Njk1MTFLMWMKLS0tIHhRc0FMek8vR0FvUndGLzlGTmhE
            OFUrUVhrUDdEcElxWkZoZkY2Q1dHTXcKz959gp62ilJ/uU15AAvlVnuiZ5Y6G3lv
            /ZRHL1Y4yiMPbaqJ8M4f6P8qKVahPEGCft30qfkY9cuhqUBUppVGmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-12T17:33:44Z"
    mac: ENC[AES256_GCM,data:Q8qrJlY0wTN/VyxX1WOc4ZXqRZxYLTui7EpVLrSef3Odi1mmCeRpEF8zwJPuA82sAu3J1hp8qvKJb5VQ+3+5gZ3Za3O4Krk3WgxSyIvUAhxtNE/VprrblRGNsIUu7T74JrwchNWp2UCy7iuWLyWbtnySsL3h/nngXM3RQSggWcI=,iv:0DR6OVKBzJuOABDKfQgxiL+Vm9Nr+VCqbhSzICH/aMs=,tag:Z33uFag7zyEPnX2kP4p7gg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
