apiVersion: v1
kind: Secret
metadata:
    name: django-email-secrets
    namespace: default
type: Opaque
stringData:
    EMAIL_HOST_USER: ENC[AES256_GCM,data:LbBOff3q5HycCqxwt2Gaw2bOmfMKKJo=,iv:AV8+Vqj5ozORytjJ9q0zvYWe0ngUWkUt42ECly38JQs=,tag:EDiqj00Tzl0nK6GSPyWROg==,type:str]
    EMAIL_HOST_PASSWORD: ENC[AES256_GCM,data:HYb9398PxTpVESNwT+nM0A==,iv:IK+JZK4RXx7jnM/1WHOxiEMSCZWnjg4neYb5UY0aQ9U=,tag:meLxCvu/e5BPQPMXkcNZ6A==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:iRy8TdTolsDuDm1uwfos0mD3Bk5H,iv:95UT03T1dWJKz3bTHzmuUDP3NY8rVwIdXxaHr8H/3ws=,tag:bPhi2CAW1E0jHkzShYzO2A==,type:str]
    DEFAULT_FROM_EMAIL: ENC[AES256_GCM,data:rd70npB6TNqTlfHM7COjXleTjztPTAo=,iv:95DYod0RRZLPAnO//PDFzmTcZ6omVMrkR2N92qG33FY=,tag:FQrj+xOr1+2Okpu6HRj1cQ==,type:str]
    ORDERS_EMAIL: ENC[AES256_GCM,data:oeBhORPi9TXgwOJ/1f34ogJhsBwAMZ8=,iv:VIwStxaDYrz1jvO4EP0luxBdv4R9Pr4fjlyFMczWVfI=,tag:ISBTkw1g6QfHAGMpdLFA5g==,type:str]
    HELP_EMAIL: ENC[AES256_GCM,data:hmgn9p35mtxKSR1Sosxg6vTZlSfo,iv:KnmjIX94oAJcHdSUgvnz1kHLNVISLNh2u9m1FXPBNtA=,tag:naxkYiA+EKhEYb7V/+DNXw==,type:str]
    MEDIA_EMAIL: ENC[AES256_GCM,data:ARbS4FZddB9rA2/AaTrXsedMaxRKCg==,iv:dOnG7jq8+KYBmTqUd+kGu4ATduXAFFRx7d6Aam9ZXJs=,tag:B67dAhWtbaCJtrndbXbGEA==,type:str]
    BUSINESS_TIME_ZONE: ENC[AES256_GCM,data:V9qfLR5Hak0E+m5bnA34,iv:gfOOpHw9/jk6GRxTpgLsZtrj+EPTe3xYOpzV5Cw4zwk=,tag:6RXt3YgD0ZRXadoZ96yDwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3QSs1eE1LS0wrWXYrZUxm
            YzhETGRlaVpwdVJCL2FUblhZNkFpcU5ZaWlBClA4UXNBa1FDZS9iNWJJNjlOY2ov
            MDA1M1FzZ0hYUGhndDVqWDdDdGFVZDgKLS0tIEg1NXRSSGw5T2xhUFMzTU44TUIx
            RTVQc2F6T2p5aksrU0JrbDJzVEZWQ3MK/5cUpmb9NoZEdWfhkfjv072ejbFyB9Ap
            qGs5C8jda3fDc9nUh+Q31bQs2Zqd+XMpv34CbNMm1Fm+h2EfHQ5xyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T04:16:24Z"
    mac: ENC[AES256_GCM,data:iBwwG8LCv7vQUkxSjGAEy2fw4C6fbJiJBeDssrf/Lu6b86dhr0ywgM/c1r+6IQ5En2ewKywTL79jhjcPkRTyf5A6qbXSBPX7DmHbzC+fWKJhwaA4thJbMyDTwDcURPb7ONBpog6oyyYT22+lgGgESg5+ca6qYccL9dN2Ozn4DL4=,iv:umsrk6pEV7r32r3Ww6aYfKWvbVdYOADclcwwoqRsIS4=,tag:Yp58bCoDXCNals5DTpJOzg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
