apiVersion: v1
kind: Secret
metadata:
    name: django-spaces-secrets
    namespace: default
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Tk5NTXSTbIvaD0kO//V9WwJYY1I=,iv:vKX2uRpkUhfs0mgOge/rJatK7I2zvs4tV67mvtHp8rA=,tag:eSd1jQrYY8GvbRKmBJ0Zjg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:A58OGnK8ozURNDshPWEunT9ZanrwIsqY/+23BTverDtA5NWI7hhb5u9JAQ==,iv:7lxHzw0wFKDQN4Lrbb/UZdk2rsXhdKpG2L3xOKnKVYo=,tag:l8KtYxhuaX/vmojF8LsIbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdUxHeU03WEw4bzIxc09p
            eG16SnlBU3VvNjdOYVVzVGlKWlM3OTZreTFZCnlOMVZlOWhZdHVSdlNxdXdqaEFS
            K0xMWjI4WkpXUlBFbi83QVR6Sml5OEEKLS0tIGt0WVNvRldGdjk1a2lrOUR4ZENX
            MTh3RFdUb1lPSkRUUmNiSlNlS1FaWEEKqi8aJyu2F/lgOxJhcYI+fXuyiV3QUwkg
            sXtAJO9TNg70hvLECQ/KCTLRrbd++s/4QVkFUiaqVEfi/PUISUapJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-08T06:54:40Z"
    mac: ENC[AES256_GCM,data:JW8J7PmPQ0BgAdXDwilRJQZ+/e0y/iVofeMGGkriqvLQyXX/gxmwJfPZhYTlfKK4CgpoaLUov4au5UnVMgI3L52J7aP7uPF0kL408PqUJ00qhKmPtNUyHw34SGHpSvtoyEYdOog1ncQQneyTNgkE/egM9o2vArK2t2okFH/AJD0=,iv:Vw8o0pcCuLDDnAIsy5RdW5dFJJW/cYj8Qa1pDJBIV1Q=,tag:2+cD4ApuE9RROdKJXV1HJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
