apiVersion: v1
kind: Secret
metadata:
    name: django-secrets
    namespace: default
type: Opaque
stringData:
    STRIPE_PUBLIC_KEY: ENC[AES256_GCM,data:v8xURlM/jQ1ZgnnV/WHAv/ncw7RFgA9mbuD1yRlPU0YXqDNRKWOd6pG2Ybgi/fK9DKGpKNArOf4XFxxdRLDNUrSwFS8EkbFS5Kanja9J7VXk0GDSTMgAwFtUgSut+XfHrSLqv2Fj8Pm7QwM=,iv:tiU2sPJAGmyHY6m12ggrP29sUWPaJr+ArllAC/bdwJk=,tag:1VrdR7AhTu3kVFvRyq1CFA==,type:str]
    STRIPE_PUBLISHABLE_KEY: ENC[AES256_GCM,data:6Lz9As5Ox/t/ggfmSICtgZz4pZ20IrMH+G0I65DwXNpzwDhkKzb4dhpnDU3sy3yngXFxUGYj6oqI4mtoQny0aF4iw3dKaEErDKelv/IDkr2Lf2mlALeRzWXnWuBk3UuhiCqCobDxYthLwaw=,iv:OPt5V3qMoBCNP1ne8dnx6euzHqq8MUCBue65jOfSMBQ=,tag:8DLRoJFAm+IB9EDj//lHHg==,type:str]
    STRIPE_SECRET_KEY: ENC[AES256_GCM,data:RA8imAuvX4n2Z2aE43Xy2supNvNAx635cFwqjFwFAwtYxZxSGa1qB9Hy7CGdtYehV+5dGyoclykSawMT81GP74qBsScZmT4Wrxo8QQDhsO3qeReuYlYC3tkLHvPogclUn23/+WMNLmg0A7Q=,iv:gDV6BS+1F0EcyyX9G6mDB3aoekQz89FmTg158I6BfTg=,tag:g60U5dglK92LeKM5oX/Yqw==,type:str]
    STRIPE_WEBHOOK_SECRET: ENC[AES256_GCM,data:wvHSoRYoa5meNl7gFE9A6gVh2zO3h+I8wZEC31AOldB5SPQ86RI=,iv:ahi0jEad4vBHLC20T/8eOfr+gswt9bGhi7u9mLfPRo0=,tag:1nN78Wb/E/JCQ6+xcgtrGQ==,type:str]
    STRIPE_WEBHOOK_SECRET_DEV: ENC[AES256_GCM,data:AiW2GSML3gR0d2l6+JjI4HLsewI+Pg4KmwJsUwl8YdBAAVp07VI=,iv:sJSRkazXv4sfY6VVczwLmoWX2RTOZhk+wAaZsNghRWA=,tag:eKQf13wmeJlMVbGpxkOvBQ==,type:str]
    STRIPE_WEBHOOK_SECRET_PROD: ENC[AES256_GCM,data:PnaJZDSOr6uEYC8i4EBcIrcO+gRx764/4k0FMf/W2kxd0FKIVyo=,iv:4HyYv/hXA+GnzFLLiLI664QFQbHFURJkjz5vlck/hHM=,tag:Pduu1OJ7W1A1psZ4O55h+A==,type:str]
    DB_HOST: ENC[AES256_GCM,data:G67KquYlJ9F8Wtoc+AbnTijvbt4YA2s+ereE70AXFChdenTJtxlyw0Bam1HnuWxWJh2/4PVJ69CsFBE4qlc71Xmdktuh7P5S1YaNQovu,iv:RXVHrkqSh1XHc0jQufaGn3BQ1E79D26k+AjpxZZ8qWg=,tag:7gbgTN6wbFRzZYFESPwWFw==,type:str]
    DB_PORT: ENC[AES256_GCM,data:yjryngk=,iv:7ZiaOsXF7JT+r/mDPntLh3gM1y0aRsta2FnbLTR5oWQ=,tag:X9yWsOdx4KepTmMgzBOR1w==,type:str]
    DB_NAME: ENC[AES256_GCM,data:Z4bf6Jdc,iv:25HXBctZnojWBPkfx571SZ3cO4GvjfS0+6Xm4IDF5aQ=,tag:kaP0Rr3XoIbgb7ssBwO7Zg==,type:str]
    DB_USER: ENC[AES256_GCM,data:eB0yLQFb3eQjcoU=,iv:Jtkn0b8E+7NqcXje0ilo6HfnmernTGqZ531rZhHi7mw=,tag:rvISWymKIoCzHioHWNDASA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:bijEsopBiV628lziJICF8dCiKdeon+dmG7KQaZw57UmIMiqQPAz7kQ==,iv:YnPb40hBd6HPT6MEAgmwzLVFQua4HIxjU9GQcmRr5g4=,tag:4H+w67SxGKYpQNjxMMjvHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQWMya2NMaUdSWDc0WERy
            aEZOQVhHbGFBcXh3VjFIZkJ3WTR4SU9hNFRFCi82dHZvVWtjcXpPWmxMbVNmdzZW
            clJoZ1NnaTUxOVZlTmRYbkM2RnhOZVkKLS0tIHdpYXFxMnh3WlZpWi9lOUJWMSs5
            UkRFV2VTZVM1NGZsenMzdnVwQStqOW8K4TxcBhJZCZ/gEHII0a/OEYSPeRLtKtLb
            7vPSWcvKOwcksiJ/fQd4OAVImYWxmkgwA2IRXKc2RRUc/Y2FMmUt8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-06T22:37:21Z"
    mac: ENC[AES256_GCM,data:7Y0Mw6dA1MNDYcL4LtCh5YJ8ExXhRfh/TCjsGwEyzQPdJof0qnPUK5KWsFeavpcfaWLot0uMA16nl451DicpIcIPtZ+zdhlzXXnfp69cSopVfKC4cKDaKfgICZ7r+H/cGoM9kE+t3HrK/m6uvAAPgyv32wqPSjHahcLGweYuUrU=,iv:XzQtZZmV/cu/oo/LmjcjgIS/r+r97meWiMKzdV/2PfQ=,tag:/c9cv46lpNcE0wfBtfH8eQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
