apiVersion: v1
kind: Secret
metadata:
    name: regcred
    namespace: default
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:90ccl+SAWyVG5Krj9ncImPUgKlaBOb9VhDcw0sx80kBEIC74qrye1v00ZXq/E4U4c4uw5ITJlEN0hXRMMi0cdnhXb7wawuLhV8v+hkBvcVqqh7mC117RzmL+RpKbym4hr+I3FnMnEqv+3GA4KVoneLfbomcwo9Ibq76C1BoaNPTxec3U5Ch5yCi571MhiZFhkVQF/jdIdm20NA3+9L8CIbNvsm8EHJJ0X4lJCMYtO4CAhJ/bmAXnCTnfBgH6JFo0fbzMrW0kIliyusVkEv1WmHomfwjrutPBBo7UZZ1uvSp1NHfsfaP2MevzuPk7wRGv6HhYqxuO9dFLRxUv4eBDq2G8OsBnZqK2uTN8/qIxgruuJiB57ijX8r1KyFIZV31Y1fFuVjwSs4eF50Nhnz91TsPUIRUMSQ4h8oq6Qnvc5u78rxmgNP25LOOOYop5S6rjnbVNVody6kWusSMpAujyHa220uZBLP/YB5gMHO+TByc3vKA9sV4VCC8ymU7/LSXuBHS4ejKZbcKbdps1BF2qdyeJ5QawqENid9AhWrXoLkDRgLLUTEC1ibRhHJsSqWUW2QaqlVoBdJsy8ylmlB4u0uUwDEDZQ1MzSQD1RLIgpjpiZNIXPF4WNDJLLlgI+/sIBmsF4U9jJc83D3UwprEIjNN9FI8mT1C99oshLj85ib95JlCKFRo/zDUa7mP1+Twjg+S/ybPQu9fKJrjKp9EfiD1dGYFtwAH3lcpO5DbkaSc+CK/oeWeJ5Drxern6lM313tpLmx1dJl/O4Dqo,iv:XquM4M3+iwCnZ6GTCZQgkmqYZ7AvoA1b16wAJ/Bh8h8=,tag:dhS8dURl07uBX4V3I4fydA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNkRFLzFJU3ZIZXZ4eWo3
            bUc2azl3cXhvMnhnd1lwWEpUaEwvT1JmQkZJCllFTkhQOWFVSkE1dGx5a1VOUTR5
            ZDB1WE5LM00rUkZvdnZ3OHFPZWpHaWcKLS0tIEYxNVRVNHFraUxJK1M4TVU3T3Iw
            NmNzczlkN0plK2VWMFB5OW1RRTVYQ0UKbVPkv43Ej80IMtbpOsTOn+MvqUigi/r4
            bO88EuxIlgZTHczoI99ktM0bKSQT/eB7sLUkQI3mN8NwJsxLCT6/Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-08T03:58:23Z"
    mac: ENC[AES256_GCM,data:YAihDRCkANkoO4hw/yEviW8FgePnJnXFzPJfdPYEd1Li7SDA4OkebEWuh735ZzimqPgttiEk7HInF5FDzMJTJWFPrd1Z0hYA3cw0XPTomCeo5Wf++SIka7NaJDoLDkvfRyjKm+fN7bkIYvqzA6yp4HyQR9U7rwAMrNRpB7FnU90=,iv:6oOIiQpd6QC1c32bEAJjEMMwJvnJ6YTP2fJ8SezUAJo=,tag:dtyfUJcbsglcJz9G9MNHqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
