{{- if and .Values.monitoring.createNamespace .Values.monitoring.namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "splattop.monitoringNamespace" . }}
  labels:
    {{- $labels := include "splattop.labels" . | fromYaml -}}
    {{- $_ := set $labels "app.kubernetes.io/name" "monitoring" -}}
    {{- toYaml $labels | nindent 4 }}
{{- end }}
