apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"
  configManagementPlugins: |
    - name: ksops
      generate:
        command: ["kustomize"]
        args: ["build", "--enable-alpha-plugins", "."]
