apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-repositories
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: splattop
  source:
    repoURL: https://github.com/cesaregarza/GarzAICluster
    targetRevision: main
    path: secrets/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 5
