apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cegarza-blog
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: splattop
  source:
    repoURL: https://github.com/cesaregarza/GarzAICluster
    targetRevision: main
    path: helm/splattop-blog
    helm:
      releaseName: cegarza-blog
      valueFiles:
        - values.yaml
        - values-cegarza.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cegarza-blog
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 5
