apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: citrus-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: splattop
  source:
    repoURL: https://github.com/cesaregarza/SplatTopConfig
    targetRevision: main
    path: secrets/citrus
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 10
