apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: garz-ai
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: splattop
  source:
    repoURL: https://github.com/cesaregarza/SplatTopConfig
    targetRevision: main
    path: helm/garz-ai
    helm:
      releaseName: garz-ai
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: garz-ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 10
