apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skyquiet-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: splattop
  source:
    repoURL: https://github.com/cesaregarza/GarzAICluster
    targetRevision: main
    path: helm/skyquiet-server
    helm:
      releaseName: skyquiet-server
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 10
