apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: splattop-teams-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: splattop
  source:
    repoURL: https://github.com/cesaregarza/GarzAICluster
    targetRevision: main
    path: helm/splattop-teams
    helm:
      releaseName: splattop-teams
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: teams-refresh-db-secrets
      jsonPointers:
        - /data
