apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: splatvote-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: splattop
  source:
    repoURL: https://github.com/cesaregarza/SplatTopConfig
    targetRevision: main
    path: secrets/splatvote-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: splatvote-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 5
