apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: splattop-prod-comp-auth-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: splattop
  source:
    repoURL: https://github.com/cesaregarza/SplatTopConfig
    targetRevision: main
    path: secrets/splattop-prod-comp-auth
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 5
