apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spotify-hot-100-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: splattop
  source:
    repoURL: https://github.com/cesaregarza/SplatTopConfig
    targetRevision: main
    path: secrets/spotify-hot-100
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 5
