{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "agent-8s.fullname" . }}
  labels: {{- include "agent-8s.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels: {{- include "agent-8s.selectorLabels" . | nindent 6 }}
{{- end }}
