{{- if .Values.permissions.postgres }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-to-external-postgres
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 10.108.0.10/32
      ports:
        - protocol: TCP
          port: 25060
{{- end }}
