apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-config
    namespace: monitoring
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:qLgGA/iVaBhaDrfeyqdEbPtWuESoq8AFU7XSocO1LB8664N7TlM00f2sPKIQmFZxoRRHALtWTVC8/Y20w0xJ1QECz3k2IqflEhnubDXqN3ezGOvE+hB8LA==,iv:quhSs34lEVMSKzbp76HLGIok8yZB5Ss1acwivk/9BlQ=,tag:CcWZVHdCev5Rwa7POY8dQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SFpQYjZpRWpHSVZSMWo3
            T3p0TXl1VmpibGU3VnN6U09kMEduMFkrQ1hBCmNNL0VxWjZNWXNmS3JQYmRFOHly
            OU5zRjhiNWNFbkVHWVM4b0RqQWxxZGsKLS0tIG1IQTNVOTd1QWdxQXZCNFNMN1hr
            MUVPcjFkQ2VDanpFNHJRdGxBaW5NVFUKwXCx3c+y7+MJOB68HxNv26ykzpxDceAD
            Q0ru2xk9M+0T1t+ewqxISH9M7sXoJ85OY0k4EZ+OqmZBp57LM82mkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T03:39:27Z"
    mac: ENC[AES256_GCM,data:kl7lF9hQXYTRIpaKvJEKR0xAfoSG5VPYZSMLsGcpNzexNdpYN4sk30dcJYaTeCRnpPx4opK2G+RdU+nmDtjmQPA6AsRLMwy7I8tZFvS4xmp5TdEHRgwzCfLNP+LY2hpt4XQ7w4di4qANcrrQpGvaYwREwEVw7XuPXq344Z55LpI=,iv:mzXdC0CMIqlIhLuB5j5KGvXMSAfmihk6l3AVLWtCPgE=,tag:Rn+pXurUKsdO2r/9aQSS0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
