{{- include "agent-workloads.citrusBroker.validate" . -}}
{{- if .Values.citrusPurchasingBroker.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agent-workloads.citrusBroker.name" . }}
  labels:
    {{- include "agent-workloads.citrusBroker.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end -}}
