apiVersion: v1
kind: Secret
metadata:
    name: regcred
    namespace: splatvote-prod
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:piRJqf6wMwc5zGcFFKcGpujOn/Jjcj/UEkls3TljthDq19ejeiJEjfSJUwy8WrbPOVNZcGgqO9JFkCYzhNs2rBE0LM5gWRuTBEL94UV1GAEBxos/DR9+ziSkOIyr8JRd3FkOEYixj719ZqmVBlXYE2xmBeEM6BDQxnikQLfsgyzxIBJDpB3RplalsTnlXt1WlPoSy3C8smDG7bC7YArQtk7HmwRxpOKYW3Ed/4FKZ8ifBWtzHtLmaWQej+yJmLobD8+rYQGN3fujfNdsUrxa3mRoU560Yve+u5qGstGqf8WEdHIR4alEHC9hS/hPtiw6msLqmb9u7XuF/VIFR33655s/zvOYcSg3cU3EP9vOgMKRPgV0Ps7rV8VkMZSWnu3ZQK84kuizDVrpClsjFLuXa0nMtvxauUbe4MidCFRmvsWNPM9FjWdjgRDQ0ggxYx/3slLTlk52Uecte0NR1/U01a7AiM9muMNOU+EJRH/7vioo9jcGtahgDlPpcjDrheXfuKHWBOe3sre2qet19SU6MHYbfYZmn1JMWYY1U5xxSBrAghLf7wx0FCqV8xfrSc8ui1nw5/f1+GOhf+/PvZxcYDCY41QtivtQgiV/uD/1aSgxmi9pwWHtcbCIkTCIVB/gDjLBAZKoT9Ls4mxoQPOeFvFNZsF0u9dE7ucE1PAH2ziO56vErH4v4GzZHHSKsjYkE9BunVzKAcYNvpmTnFatHc2mHhnuVoq5,iv:P9UkpA8L3CzH8pQyvEEkjPix0izfK3v5Xq+0VEwnwoo=,tag:F0/3YfH0D7DXW7bDeAKTIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbEFwV01rZlN1OEpXZ2px
            ZktIV0UvMXEyYzltSzlBVEVCaHBsVTA2U0FVCmlWdXR4QnBvM01nQy9BWGx0dDRG
            N3RoNWFPTElIaFBEaUQ3dldHS0RRVkkKLS0tIGZ2enp3dEtjTlRLTFpNUFBBLzcy
            MXJaUSt3ZGlIV1NIempxUXM4anFwaEEKv1bxnv4qVI9vbsJMt6AO/eE4K6gyYWx9
            060qzd25Y31w5UucytnAn9ZXWyqoSWeoz/SLHKYhAWkl2wpeFHmjHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T07:36:34Z"
    mac: ENC[AES256_GCM,data:oCn3ykuakL1+NSx2L/KUJc3EDISegudo1X7FO80kC7LufdjFeBCNX/R0psh2q4DeZB0wn4u6DhrILUlJSsmi9//GzHB/922j2sELFgyLNIOhMcyzf3IjanNdAT1XPon+C5nct/Q8ccpkY8QzoLxn4ZkQXrVD2Iy7brsUrfXa9tM=,iv:XS9R0KBm3pItHukqSePmRHTo1ms9phB7r7ozBs9e1uI=,tag:sP/F/3SOEZZSfUlUPl+v/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
