apiVersion: v1
kind: Secret
metadata:
    name: vote-db-secrets
    namespace: splatvote-prod
stringData:
    DB_HOST: ENC[AES256_GCM,data:iHcEK0xy1yB7Q6y3N7p8a413BffxdN7FXyvDwQiOsSXhiHROTBpanX4Mq7W+7HKeoRcFAsNzS7USGLDDQNgC12sw4I+4RPIOZqQlLyZ7,iv:LEmeamp6gaPqHcmrptDFYDRZsdTSFgK8MHdFUZ7Lk8Y=,tag:0oXsk7c4KWEFHS1I4Caz1A==,type:str]
    DB_PORT: ENC[AES256_GCM,data:shm39l8=,iv:WimQn1FBQExW5Wf7a8o0NJhiqV4OP8i7lPrvZAdzah0=,tag:jGTHkSfzuc7hA3Iz9FDapA==,type:str]
    DB_USER: ENC[AES256_GCM,data:r48sY5TjUAeKWGeHTgs=,iv:INndUbk4vyBYk8pPUv8EREvju1z7cNuy0TxF2QnzS8w=,tag:CeEDvoyy3fh4RYvleNNl7A==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:c8MCFgh0ANajktcxqonte3nfaE+ymMvOgHF4sPTMjcJnvkUW+BCZrA==,iv:VxMkaQfD8Ea+sf2nfBL6Y5Jrm3MQ955xNC0ZOSjPgGE=,tag:6OLCGUBLkexRmXVvgK4kJg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:Oux1G1pkZyZG,iv:oxHR1lXZ5vceBYrNQqbKy3G2Hz4mmowfwZInuCN49ck=,tag:YK7ZPcdNtmQEFaeQAfQJwA==,type:str]
    VOTE_IP_PEPPER: ENC[AES256_GCM,data:RZuJEPPADXT4kheVq0olrlUNBAS/NyZk5idgYnHEu3GfwWvcPfA7sBCXUg==,iv:94/jdoKO2ZHU25qgWNWLUVeSw0cVW7lZn0SXaOCbk70=,tag:gamw+e8k/DQeKV09zx+7ww==,type:str]
    ADMIN_TOKEN_PEPPER: ENC[AES256_GCM,data:CIqRl4yIPbMifUQAsWd5y0VHOYknsb96bMG5k+bfQH50F8MB3schkGIozg==,iv:XusQOr+yepp3xYQ9MNOVnqV65hh/6mVYZ66vQ5fykb8=,tag:+uHhW4XYIyUjclw77FxciA==,type:str]
    ADMIN_API_TOKENS_HASHED: ENC[AES256_GCM,data:6Jg9oIrdKA+hcdVSCcQ/SVTr/Q7aWuQm/O/gtIfpq5pK/HCD5YFOcJtCnZNQfBqw/MT8g6Fv8MIjtFewGsWmMw==,iv:BzxJbOfrXJaaAeqIuUjwgIrrl9n6PYzEG+kUsiGLpdg=,tag:81w7syzrrmTZKXs6CqJfBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2azJETTc3NCtRdThLUjFS
            NnhiV2dXeWsreGlack5Jb3BBN29wVUFRMUNFClN2WitRZHAyQklGWDhZZjZlUXlw
            SmRkQ2QwSFdPMDZUWWVGdkk2R0d1WTQKLS0tIHYxazlSNFZqbzJxall2Wkdzc0dK
            RlhyZTRMZzh3VUF3MVV2RE9zcFlHVkEKicM48UzhFH8L2Ft0GwZYz7AerKE3IECw
            VBvtItVzfZ+12a10btd9MYXHVcaNqY/bT3FKKw97G0n5L2DdpnQHfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T07:36:34Z"
    mac: ENC[AES256_GCM,data:OV81DQAv/Q6WDQqyP1Ceo1Bs0bw4WCFnzB/5pmB6+BPjdOLvppgIDocoM7r6feSGop2LWg4oIm2WwrtiIW2DQxUIIYCXHfXnIZkXpIOAajTootmuh/Rvcax4u97EDDxGmwnwm5NvUlc2DBcpuP5j6NLBcxFz6GCKceJ7kNYwOHs=,iv:wEJ1GisyaRMx0+JrYSM04vffAD0arr7lQ1fKDLSM55I=,tag:0kP4/ZaeQoIAtgB0VgiZlw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
